import {ROUTES,BOOK_PATHS,diagnose,capacity,csvText} from './logic.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,body){
 const init={credentials:'include'};if(body!==undefined){init.method='POST';init.headers={'Content-Type':'application/json'};init.body=JSON.stringify(body);}
 const r=await fetch(path,init);if(r.status===401){location.href='/login.html';throw Error('Your session expired. Sign in again.');}
 if(!r.ok){let reason;try{reason=(await r.json()).error;}catch{}throw Error(reason||`Could not save (${r.status}). Try again.`);}return r.json();
}
function status(el,msg){if(el)el.textContent=msg;}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function selectedPanel(track){const r=ROUTES[track];if(!r)return;
 $$('[data-track-panel]').forEach(p=>{p.replaceChildren();const k=document.createElement('span');k.className='eyebrow';k.textContent='Selected track · saved to your account';const h=document.createElement('h2');h.textContent=r.label;const text=document.createElement('p');text.textContent=r.action;const actions=document.createElement('div');actions.className='actions';const a=document.createElement('a');a.className='button';a.href=r.first;a.textContent='Start the next guide';const b=document.createElement('a');b.href='/checklist.html#tasks';b.textContent='Open my tasks';const change=document.createElement('a');change.href='/quiz.html';change.textContent='Change track';actions.append(a,b,change);p.append(k,h,text,actions);});
 if($('#task-track')){$('#task-track').value=r.list;loadTasks();}
}
async function saveTrack(track){if(!ROUTES[track])return;await api('/api/track',{track});selectedPanel(track);return ROUTES[track];}
$$('[data-select-track]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await saveTrack(b.dataset.selectTrack);}catch(e){const p=b.closest('section'),s=p.querySelector('[data-track-status]')||document.createElement('p');s.setAttribute('role','alert');s.textContent=e.message;if(!s.parentNode)p.append(s);}finally{b.disabled=false;}}));
if($('[data-track-panel]'))api('/api/track').then(d=>{if(d.track)selectedPanel(d.track);else if($('#task-track'))loadTasks();}).catch(e=>{status($('[data-track-status]'),e.message);if($('#task-track'))loadTasks();});
const quiz=$('#track-quiz');
function quizResult(track){const r=ROUTES[track],panel=$('#quiz-result');panel.hidden=false;panel.replaceChildren();const h=document.createElement('h2');h.textContent='Saved: '+r.label;const p=document.createElement('p');p.textContent=r.action;const a=document.createElement('a');a.className='button';a.href='/checklist.html';a.textContent='Open my next steps';panel.append(h,p,a);panel.scrollIntoView({behavior:'smooth',block:'center'});}
async function saveQuiz(track){try{status($('#quiz-status'),'Saving your route…');await saveTrack(track);quizResult(track);status($('#quiz-status'),'Saved to your account. Your existing notes and tasks are kept.');}catch(e){status($('#quiz-status'),e.message);}}
if(quiz)quiz.addEventListener('submit',async e=>{e.preventDefault();const values=[...new FormData(quiz).values()];if(values.length!==6)return;const track=diagnose(values);if(track){const b=quiz.querySelector('button');b.disabled=true;try{await saveQuiz(track);}finally{b.disabled=false;}}else{const panel=$('#quiz-result');panel.hidden=false;panel.innerHTML='<h2>Both routes fit your answers.</h2><p>Choose the first output you can finish. You can switch later without losing your work.</p>';for(const t of ['service','product']){const b=document.createElement('button');b.textContent='Choose '+ROUTES[t].label;b.addEventListener('click',async()=>{b.disabled=true;try{await saveQuiz(t);}finally{b.disabled=false;}});panel.append(b);}panel.scrollIntoView({behavior:'smooth',block:'center'});}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(b){const text=b.closest('.prompt').querySelector('pre').textContent;try{await navigator.clipboard.writeText(text);b.textContent='Copied';setTimeout(()=>b.textContent='Copy prompt',1600);}catch{const range=document.createRange();range.selectNodeContents(b.closest('.prompt').querySelector('pre'));const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);b.textContent='Selected: copy with your keyboard';}}
 const route=e.target.closest('[data-route]');if(route){$$('[data-route]').forEach(x=>x.setAttribute('aria-pressed',String(x===route)));$$('[data-route-content]').forEach(x=>x.hidden=x.dataset.routeContent!==route.dataset.route);}
});
function filterPrompts(){const q=($('#prompt-search')?.value||'').toLowerCase(),cat=$('#prompt-filter')?.value||'all';let count=0;$$('[data-prompt-item]').forEach(x=>{x.hidden=!((cat==='all'||cat===x.dataset.category)&&x.textContent.toLowerCase().includes(q));if(!x.hidden)count++;});status($('#prompt-count'),count+' prompts shown');if($('#prompt-empty'))$('#prompt-empty').hidden=count>0;}
$('#prompt-search')?.addEventListener('input',filterPrompts);$('#prompt-filter')?.addEventListener('change',filterPrompts);
$('[data-download-prompts]')?.addEventListener('click',()=>download('blueprint-50-action-prompts.txt',$$('[data-prompt-item]').map(x=>x.querySelector('.tag').textContent+'\n'+x.querySelector('h3').textContent+'\n\n'+x.querySelector('pre').textContent+'\n\n'+x.querySelector('.muted').textContent).join('\n\n---\n\n')));
$('#book-filter')?.addEventListener('change',e=>$$('[data-book-track]').forEach(x=>x.hidden=e.target.value!=='all'&&x.dataset.bookTrack!=='both'&&x.dataset.bookTrack!==e.target.value));
function calculate(){const ids=['credits','attempt-cost','attempts','shots','extra','plan-cost'],v=ids.map(id=>$('#'+id).value.trim()===''?NaN:Number($('#'+id).value));const r=capacity({credits:v[0],cost:v[1],attempts:v[2],shots:v[3],extra:v[4],price:v[5]});status($('#credit-result'),r?`${r.perEdit.toLocaleString()} credits per finished edit · up to ${r.edits} edits under these assumptions. ${r.edits?`Subscription cost per estimated edit: ${r.perEditCost.toFixed(2)} in your entered currency.`:'The balance does not cover one complete edit.'}`:'Enter valid numbers. Attempt cost must be above zero; attempts and shots must be at least one.');}
if($('#credit-calculator')){calculate();$('#credit-calculator').addEventListener('input',calculate);$('#credit-calculator').addEventListener('submit',e=>e.preventDefault());}
const progress=$$('[data-progress]');if(progress.length){api('/api/progress').then(map=>progress.forEach(b=>b.checked=!!map[b.dataset.progress])).catch(e=>{const p=document.createElement('p');p.className='status';p.textContent=e.message;progress[0].parentNode.after(p);});progress.forEach(b=>b.addEventListener('change',async()=>{b.disabled=true;const wanted=b.checked;try{await api('/api/progress',{module:b.dataset.progress,done:wanted});let s=b.parentNode.querySelector('.inline-status');if(!s){s=document.createElement('span');s.className='inline-status';s.setAttribute('role','status');b.parentNode.append(s);}s.textContent='Saved';}catch(e){b.checked=!wanted;let s=b.parentNode.querySelector('.inline-status');if(!s){s=document.createElement('span');s.className='inline-status';s.setAttribute('role','alert');b.parentNode.append(s);}s.textContent=e.message;}finally{b.disabled=false;}}));}
let tasksVersion=0,taskRows=[];
function taskStats(){const done=taskRows.filter(x=>x.done).length,total=taskRows.length,pct=total?Math.round(done/total*100):0;$('#task-progress').value=pct;status($('#tasks-status'),`${done} / ${total} tasks complete · changes save to your account`);window.dispatchEvent(new CustomEvent('journalProgress',{detail:{pct,done,total}}));
 const box=$('#next-task'),next=taskRows.find(x=>!x.done);box.hidden=false;box.replaceChildren();const k=document.createElement('span');k.className='eyebrow';k.textContent=next?'Next unfinished task':'This list is complete';const h=document.createElement('h3');h.textContent=next?next.title:'Review the work and actual results';const p=document.createElement('p');p.textContent=next?next.detail:'Use feedback and your scorecard to choose one improvement.';box.append(k,h,p);const letter=next?.detail.match(/(?:^|\s)([A-J])\./)?.[1];if(letter||!next){const a=document.createElement('a');a.className='button';a.href=BOOK_PATHS[letter||'D'];a.textContent='Open the matching guide';box.append(a);}
}
async function loadTasks(){if(!$('#task-list'))return;const version=++tasksVersion,track=$('#task-track').value;status($('#tasks-status'),'Opening saved tasks…');try{const d=await api('/api/journal/checklist?track='+track);if(version!==tasksVersion)return;taskRows=d.tasks;renderTasks();taskStats();}catch(e){if(version===tasksVersion)status($('#tasks-status'),e.message);}}
function renderTasks(){const box=$('#task-list');box.replaceChildren();for(const row of taskRows){const item=document.createElement('article');item.className='task';item.dataset.done=!!row.done;const top=document.createElement('label');top.className='task-top';const check=document.createElement('input');check.type='checkbox';check.checked=!!row.done;const title=document.createElement('span');title.className='task-title';title.textContent=row.title;top.append(check,title);const detail=document.createElement('p');detail.textContent=row.detail;detail.className='muted';const notes=document.createElement('details'),summary=document.createElement('summary');summary.textContent='My notes'+(row.note?' · saved':'');const field=document.createElement('textarea');field.value=row.note||'';field.maxLength=5000;field.setAttribute('aria-label','Notes for '+row.title);const save=document.createElement('button');save.className='secondary';save.textContent='Save note';const msg=document.createElement('span');msg.className='inline-status';msg.setAttribute('role','status');notes.append(summary,field,save,msg);item.append(top,detail,notes);const m=row.detail.match(/(?:^|\s)([A-J])\./);if(m){const a=document.createElement('a');a.href=BOOK_PATHS[m[1]];a.textContent='Open playbook '+m[1];item.append(a);}box.append(item);
 check.addEventListener('change',async()=>{check.disabled=true;const desired=check.checked;try{await api('/api/journal/checklist',{action:'toggle',id:row.id,done:desired});row.done=desired;item.dataset.done=desired;taskStats();}catch(e){check.checked=!!row.done;status($('#tasks-status'),e.message);}finally{check.disabled=false;}});
 save.addEventListener('click',async()=>{save.disabled=true;try{await api('/api/journal/checklist',{action:'note',id:row.id,note:field.value});row.note=field.value;msg.textContent='Saved';summary.textContent='My notes · saved';}catch(e){msg.textContent=e.message;}finally{save.disabled=false;}});
 if(row.is_custom){const del=document.createElement('button');del.className='secondary';del.textContent='Delete personal task';del.addEventListener('click',async()=>{del.disabled=true;try{await api('/api/journal/checklist',{action:'delete',id:row.id});loadTasks();}catch(e){msg.textContent=e.message;del.disabled=false;}});notes.append(del);}
 }}
$('#task-track')?.addEventListener('change',loadTasks);$('#refresh-tasks')?.addEventListener('click',async e=>{e.target.disabled=true;try{await api('/api/journal/checklist',{action:'generate',track:$('#task-track').value});await loadTasks();}catch(err){status($('#tasks-status'),err.message);}finally{e.target.disabled=false;}});
$('#add-task')?.addEventListener('submit',async e=>{e.preventDefault();const input=e.target.elements.title,b=e.target.querySelector('button');b.disabled=true;try{await api('/api/journal/checklist',{action:'add',track:$('#task-track').value,title:input.value.trim()});input.value='';loadTasks();}catch(err){status($('#tasks-status'),err.message);}finally{b.disabled=false;}});
let sheetData=null,sheetVersion=0;
async function loadSheet(){if(!$('#sheet-table'))return;const version=++sheetVersion;status($('#sheet-status'),'Opening saved rows…');try{const d=await api('/api/journal/sheets?type='+$('#sheet-type').value);if(version!==sheetVersion)return;sheetData=d;renderSheet();status($('#sheet-status'),'Edit a cell, then leave it to save. Export a backup whenever you need.');}catch(e){if(version===sheetVersion)status($('#sheet-status'),e.message);}}
function renderSheet(){const table=document.createElement('table'),head=document.createElement('thead'),hr=document.createElement('tr');for(const col of sheetData.columns){const th=document.createElement('th');th.textContent=col;th.scope='col';if(sheetData.widths[col])th.style.minWidth=sheetData.widths[col];hr.append(th);}head.append(hr);table.append(head);const body=document.createElement('tbody');const sheet=sheetData;for(const row of sheet.rows){const tr=document.createElement('tr');for(const col of sheet.columns){const td=document.createElement('td'),options=sheet.dropdowns[col];let input;if(options){input=document.createElement('select');const all=['',...options];if(row[col]&&!all.includes(row[col]))all.push(row[col]);for(const value of all){const o=document.createElement('option');o.value=value;o.textContent=value||'—';input.append(o);}}else input=document.createElement('input');input.value=row[col]??'';input.setAttribute('aria-label',`${col}, row ${row.row_idx+1}`);input.addEventListener('change',async()=>{const previous=row[col],value=input.value;row[col]=value;const controls=[...tr.querySelectorAll('input,select')];controls.forEach(x=>x.disabled=true);status($('#sheet-status'),'Saving row '+(row.row_idx+1)+'…');try{const data={};for(const c of sheet.columns)data[c]=row[c]??'';await api('/api/journal/sheets',{type:sheet.sheet_type,row_idx:row.row_idx,data});if(sheetData===sheet)status($('#sheet-status'),'Row '+(row.row_idx+1)+' saved.');}catch(e){row[col]=previous;input.value=previous??'';if(sheetData===sheet)status($('#sheet-status'),e.message+' Your previous value is restored.');}finally{controls.forEach(x=>x.disabled=false);}});td.append(input);tr.append(td);}body.append(tr);}table.append(body);$('#sheet-table').replaceChildren(table);}
$('#sheet-type')?.addEventListener('change',loadSheet);$('#sheet-export')?.addEventListener('click',()=>{if(sheetData)download('blueprint-'+sheetData.sheet_type+'.csv',csvText(sheetData.columns,sheetData.rows),'text/csv');});$('#sheet-add')?.addEventListener('click',async e=>{e.target.disabled=true;try{await api('/api/journal/sheets',{type:$('#sheet-type').value,action:'add-row'});await loadSheet();}catch(err){status($('#sheet-status'),err.message);}finally{e.target.disabled=false;}});if($('#sheet-table'))loadSheet();

$$('[data-brand-image]').forEach(img=>img.addEventListener('error',()=>img.hidden=true));
