"""Twenty bounded starting offers. Times are editorial practice estimates, not guarantees."""
SERVICES=[]
def service(id,name,buyer,sell,hours,skill,pro,con,inputs,sample,recipe,check,channels,prompt,tags,paid):
 SERVICES.append(dict(id=id,name=name,buyer=buyer,sell=sell,hours=hours,skill=skill,pro=pro,con=con,inputs=inputs,sample=sample,recipe=recipe,check=check,channels=channels,prompt=prompt,tags=tags,paid=paid,kind='service',source='https://www.upwork.com/research/in-demand-skills-2026',evidence='Upwork’s 2026 report includes related creative, marketing or admin skills. Its data comes from US client spending in 2025. This small package is our suggested starting scope, not a reported bestseller.'))
service('website','One-page business website','Tutors, tradespeople, photographers or consultants','One mobile-friendly page: clear offer, services, FAQs and a contact link. One agreed revision.','6–12 hours','Patient with testing. You can start without programming, but must test what AI builds.','Easy to show a working before-and-after.','Forms, checkout and custom features add complexity. Don’t promise them in the starter package.','Approved business facts, contact link, logo/photos you may use, preferred colors and page goal.','A fictional tutor’s page with a lesson enquiry button. Label it a demo.',[
 'Pick one business type you understand. Write three common customer questions and one useful next action.',
 'Open ChatGPT, Claude or Z.ai. Paste the website prompt below with those facts. Ask for one self-contained index.html file. Copy only the HTML, without markdown fences, and save it in a new folder. The included website-starter.txt is also a complete editable practice page. Rename a copy to index.html before opening or uploading it.',
 'On Windows use Notepad → Save as → All files → index.html → UTF-8. On Mac use TextEdit → Format → Make Plain Text → save index.html without .txt. Open the file in a browser.',
 'Ask the AI to fix one problem at a time. Paste the relevant code and say what you clicked, expected and saw. Replace sample contact links before sharing.',
 'Open Cloudflare dashboard → Workers & Pages → Create application → Pages / Get started → Drag and drop. Choose a project name, upload the folder and select Deploy site. Labels may move. Use the Direct Upload source below if they differ.',
 'Open the pages.dev URL on your phone. Tap every contact link and check text at a narrow width. Send this preview to a suitable buyer, with permission.',
 'For paid delivery, agree the client-owned account, domain cost, maintenance and changes in writing. Send files and a short update guide. A static page has no working payment system or database by default.'
], 'Every link works, phone text fits, facts are approved, images have rights, and a new visitor can find the contact button. No fake working form.', ['Maps + websites','Instagram','LinkedIn','Facebook Groups'], 'Build one self-contained index.html with inline CSS and minimal JavaScript for this fictional demo: [business type], [reader], [offer], [approved facts], [contact URL]. First ask for missing essential facts. Include headline, services, three FAQs, and one clear contact link. Responsive layout, semantic HTML, readable contrast and visible keyboard focus. No framework, backend, checkout, fake reviews or unsupported claims. Do not make a form appear to submit. Give the complete file, saving instructions and a link-by-link phone test. Mark fictional demo visibly.', ['visual','build','patient'], 'Optional Vercel Pro or a paid builder for commercial projects. Vercel Hobby is restricted to personal, non-commercial use. Shopify is usually simpler for a real store with checkout and orders.')
service('copy','Landing-page copy','Consultants, course creators, local services or software teams','Rewrite one page: headline, short introduction, three benefits, five FAQs and one next-step button.','3–6 hours','Comfortable rewriting plain sentences and checking facts.','You can demonstrate the improvement in a two-page document.','Good copy needs real buyer information. AI cannot invent proof or customer research.','Current page, audience, offer, approved facts and chosen next step.','A tutor’s vague headline rewritten to explain lessons, who they help and how to enquire.',[
 'Open the current page. Copy its headline, introduction and next-step button into Google Docs.',
 'Write who the reader is, what they need and what the business actually offers. Leave unknown facts as questions for the owner.',
 'Paste the prompt below into your writing tool. Compare three headlines and choose the clearest, not the most dramatic.',
 'Build a two-column Before / Suggested version table. Add three bullets explaining your changes.',
 'Read the final page aloud. Delete invented statistics, testimonials and guarantees. Export a PDF and include editable text.'
], 'The headline names the offer, every benefit is supported, and the reader knows what to do next.', ['Instagram','LinkedIn','Facebook Groups','Websites'], 'Rewrite this page using only supplied facts: [current text], [reader], [offer], [approved evidence], [next step]. Ask up to five questions if essential information is missing. Give three plain headlines, a 60-word introduction, three supported benefits, five FAQs and one button label. Add a Before / After explanation. Mark unknowns. No invented testimonials, conversion claims or urgency.', ['words','research','short'], 'Optional longer-context writing subscription. Free Docs + a free writing tier can produce the starter file.')
service('design','Social posts and carousel design','Creators, small shops, educators or service businesses','Three post designs and one five-slide carousel using supplied copy and brand assets.','4–8 hours','Enjoy spacing, typography and visual consistency.','A clear visual sample is easy to judge.','Design skill still matters. Premium assets and editable template rights must be checked.','Approved text, logo, colors, image rights and platform size.','A photographer’s five-slide booking FAQ plus three matching post layouts.',[
 'Open Canva → Create a design → Custom size → 1080 × 1350 px. Use a blank page and free assets.',
 'Choose two fonts, one accent color and one background. Put one main point on each page.',
 'Paste approved copy into five pages: question, common problem, useful step, example, next action.',
 'Duplicate the best layout to make three single-image posts. Keep margins and font sizes consistent.',
 'Download PNGs, open them on your phone and read without zooming. Deliver exported images and an editable link only if your asset rights allow it.'
], 'Readable on a phone, no spelling mistakes, and every image/element is licensed for the agreed use.', ['Instagram','Facebook Groups','LinkedIn'], 'Plan one five-slide carousel and three post layouts for [buyer], [topic], [approved copy], [brand colors]. Use simple wording and one point per slide. Give headline, short body, image suggestion and layout directions for each. Avoid fake metrics and claims. Then check whether slide five gives the agreed next step.', ['visual','short','organize'], 'Canva Pro is optional for brand features. Check licensing before selling editable designs. Original layouts are the safer starting point.')
service('video','Short-video editing','Podcasters, coaches, shop owners or creators','Three vertical clips of 20–40 seconds from supplied footage, with cuts and checked captions.','4–8 hours','Enjoy timing, listening and careful caption checks.','Uses existing footage, so you don’t need a filming studio.','Poor source audio is hard to fix. Agree revisions and source length before quoting.','Footage rights, source files, clip goals, correct names and approved CTA.','A fictional creator’s 30-second FAQ edited from your own recording.',[
 'Record your own 60-second explanation for practice. Ask a real client to supply footage they have permission to use.',
 'Open VN or CapCut → New project → add footage. Set vertical 9:16 / 1080 × 1920.',
 'Cut the opening pause. Keep one useful answer, place the clear result early and remove repeats.',
 'Add captions using available free features or manually. Correct names, numbers and punctuation. Keep text clear of interface buttons.',
 'Export 1080p MP4, play with sound and muted, and send three named clips with one agreed revision round.'
], 'Captions match speech, cuts make sense, audio is clear and the final file plays on a phone.', ['Instagram','YouTube + public business email','LinkedIn','Facebook Groups'], 'From this authorized transcript [text], choose three standalone 20–40 second clips for [audience]. Give exact start/end lines, hook, what to remove, caption corrections and one CTA. Do not invent speech or imply a result the footage does not show. Return a simple editing checklist.', ['visual','patient','media'], 'Optional editor subscription for a specific feature. Test a free export before paying. Generated clips are optional inserts, not proof of product performance.')
service('social','Weekly captions and posting plan','Small shops, tutors, consultants or creators','Seven captions, a seven-day posting plan and three simple image suggestions. Posting and account management are separate.','4–7 hours','Good at understanding questions and organizing ideas.','Small scope with a clear finished file.','You need owner-approved facts. Seven posts do not guarantee reach or sales.','Offer, reader, common questions, photos, links and approved facts.','Seven useful posts for a repair business explaining enquiries, assessment and next steps.',[
 'Open a blank Google Sheet. Add Day, Reader question, Post idea, Caption, Image, Next step and Approved columns.',
 'Collect five real customer questions from the owner or public posts. Paste approved facts into the writing prompt.',
 'Draft seven captions. Make each answer one question. Avoid seven versions of the same pitch.',
 'Read every caption aloud and check each fact with the owner. Fill one clear next step per post.',
 'Deliver the Sheet plus a PDF preview. Ask for approval before publishing or claiming the work as a client example.'
], 'Seven different useful points, working links and no invented price, result or business fact.', ['Instagram','Facebook Groups','Maps + websites'], 'Create seven posts for [buyer] using only [approved facts] and [real customer questions]. Return Day, reader question, post idea, 60–100 word caption, image suggestion and next step. Vary tutorial, FAQ, example and offer posts. Mark missing information. No invented customer stories, discounts or reach claims.', ['words','organize','short'], 'Optional Canva or writing subscription after your first free export. Account scheduling is a different scope.')
service('listings','Product listing descriptions','Small ecommerce shops or makers','Titles, descriptions, five FAQs and image text for five approved products.','3–6 hours','Careful with measurements, materials and buyer questions.','Clear checklist and manageable first project.','You cannot infer specifications or safety claims from a photo.','Verified product facts, photos, price, shipping/returns facts and shop platform.','A desk organizer listing with checked dimensions, contents and a fit FAQ.',[
 'Ask for a product fact sheet with dimensions, materials, package contents and approved claims.',
 'Open Google Docs. Create one section per product with the original text and confirmed facts.',
 'Paste the prompt below. Write a clear title, factual description and answers to likely fit questions.',
 'Compare every measurement and claim with the fact sheet. Ask the owner about gaps instead of guessing.',
 'Deliver five editable listings and a check sheet. Uploading to the shop is optional and requires separate authorized access.'
], 'All five listings match actual products and explain size, contents, compatibility and the real next step.', ['Instagram','Shop websites','Facebook Groups','LinkedIn'], 'Write five listings from these verified product sheets [facts]. For each give a plain title, a 100-word description, five FAQs and three image-text suggestions. Do not infer material, compatibility, shipping, reviews or benefits that are not supplied. Return a missing-facts list and a fact-to-claim check table.', ['words','research','patient'], 'Optional paid writing tool for larger catalogs. Use client-owned Shopify or another supported store for checkout, tax, shipping and order management.')
service('emails','Three welcome or follow-up emails','Newsletter writers, creators, stores or consultants','Three emails for people who signed up, enquired or bought, with subjects and next steps.','3–6 hours','Comfortable writing conversationally and planning a sequence.','Easy to show as a small document.','You need a real audience and lawful sending setup. Writing does not include automatic emailing.','Who opted in, what they requested, approved offer, brand voice and links.','Three welcome emails for a fictional workshop: access, first useful step, FAQ.',[
 'Ask what the subscriber requested and what should happen after each email. Do not collect a mailing list for practice.',
 'In Docs write Email 1: deliver the promised item. Email 2: help them use it. Email 3: answer one question and offer the next step.',
 'Use the prompt below, then shorten robotic phrases and check each link.',
 'Preview on a phone. Send a test only to yourself or an authorized tester using the client’s permitted setup.',
 'Deliver subject, preview text and body for each email. Include timing suggestions for the client to approve.'
], 'The promised item comes first, links work, the tone is clear and the sender’s actual unsubscribe settings are checked before launch.', ['LinkedIn','Instagram','Facebook Groups','Websites'], 'Draft three emails for people who explicitly requested [resource or signup]. Facts: [offer], [reader], [links], [voice]. Email 1 delivers access, Email 2 teaches a first action, Email 3 answers an objection and offers one next step. Give subject, preview and body under 160 words. No invented urgency, testimonials or automatic sending.', ['words','organize','short'], 'Optional client-owned email platform with a verified plan. The free route can deliver copy in Docs without configuring automation.')
service('slides','Presentation cleanup','Consultants, educators, agencies or small teams','Make a supplied ten-slide deck readable and consistent. Content strategy and investor claims are excluded.','4–8 hours','Like organizing information and checking visual order.','Existing text gives you a clear starting point.','Last-minute changes expand the work. Agree slide count and revision limit.','Existing deck, audience, speaking goal, logos/photos and approved figures.','Three messy workshop slides rebuilt with one message per slide.',[
 'Ask for the current deck and the one thing the audience should understand or do.',
 'Open Google Slides → Blank presentation. Set 16:9 unless the client specifies another format.',
 'Turn each slide title into one clear sentence. Keep three short supporting points or one visual.',
 'Apply two fonts, matching heading positions and one accent color. Preserve the meaning of every number.',
 'Export PDF, check slides at presentation size and deliver the editable deck with an agreed revision round.'
], 'No changed figures, text is readable at normal viewing size, and slide order supports the speaking goal.', ['LinkedIn','Facebook Groups','Websites'], 'Simplify this deck for [audience] to understand [goal]. Supplied slide text and verified figures: [text]. Return one message per slide, shorter bullets, visual suggestion and speaker note. Do not invent market sizes, investor traction or results. Flag facts needing approval. Keep ten slides.', ['visual','organize','patient'], 'Canva Pro or paid slide tools are optional. Free Google Slides is enough for the starter package.')
service('research','Verified business research list','Agencies, consultants or service sellers','Ten suitable businesses with source links, visible need, public business contact route and checked date. No purchased personal data.','3–6 hours','Like investigating and checking sources carefully.','Useful for many client types. You can show a clean ten-row sample.','AI can invent details. Research does not mean buyers consented or will purchase.','Client’s offer, buyer type, location if relevant, excluded businesses and permitted research channels.','A five-row practice list with opened source links and honest unknown fields.',[
 'Agree the target and exclusions before searching. Use the research chapter’s Instagram, Groups, LinkedIn and Maps paths.',
 'Create a Sheet with Business, Source URL, Checked date, Observation, Why it fits, Public contact route and Unknowns.',
 'Use the two-stage research prompt if helpful. Request a small batch first. Keep inaccessible sources as unknown.',
 'Open every source and check names, location, business relevance and contact route. Remove duplicates and personal details.',
 'Deliver ten checked rows plus search notes and limits. Do not send messages or claim purchase intent as part of a research-only package.'
], 'Every row has a checked public source. No invented contacts, private personal details or promised leads.', ['LinkedIn','Facebook Groups','Agency websites','Instagram'], 'Using these permitted public sources [URLs], research businesses for [offer], [buyer], [location or remote]. Return business name, URL, dated visible observation, why the offer may fit, public business contact route and unknowns. Do not scrape behind login, collect personal contact data, invent budgets or message anyone. Separate verified facts from suggestions. Stop after ten checked rows or explain the shortfall.', ['research','patient','organize'], 'Manus Pro Wide Research is optional and consumes credits. Free manual research and smaller agent batches are viable. Z.ai can organize supplied sources without paid API access.')
service('workflow','Simple enquiry form and tracker','Freelancers, tutors, consultants or small teams','One enquiry form connected to a Sheet, with a clear status column and short use guide. No custom app or sensitive-data system.','4–8 hours','Patient with settings and testing a small process.','A visible working demo is easy to explain.','Access, privacy and ownership need care. Complex automation is a different service.','Needed fields, who should see responses, follow-up process and client-owned Google account.','A fictional tutor’s enquiry form feeding a lesson-request Sheet.',[
 'On your own practice account open Google Forms → Blank form. Add name, business email, requested service and one optional note. Use fake test data.',
 'Click Responses → Link to Sheets → Create a new spreadsheet. Submit one practice response.',
 'Open the Sheet. Add Status, Follow-up date and Owner columns. Use Data → Data validation to add New, Replied, Agreed and Closed status choices.',
 'Check sharing settings. Do not publish response data. Test the public form link in a private browser window.',
 'For delivery recreate or transfer the setup into the client’s approved account, agree access and give a one-page guide. Don’t ask them to share passwords.'
], 'A test enquiry reaches the Sheet, private data stays private, permissions match the client’s approval and the owner can update a status.', ['Facebook Groups','LinkedIn','Maps + websites','Instagram'], 'Design a simple Google Forms → Sheets enquiry workflow for [buyer], [process]. Ask which fields are genuinely needed. Give exact form questions, tracker columns, status choices and a three-case test plan. No sensitive-data fields, passwords, backend, automatic messaging or paid integrations. Explain ownership and access in plain language.', ['build','organize','patient'], 'Paid automation tools are optional after a tested manual workflow. Do not include subscriptions or ongoing support without an agreed price.')

PRODUCTS=[]
def product(id,name,buyer,sell,hours,pro,con,contents,recipe,check,demo,source,evidence,tags,kind='download'):
 PRODUCTS.append(dict(id=id,name=name,buyer=buyer,sell=sell,hours=hours,skill='Be willing to test the file with someone who has not seen it.' if kind=='download' else 'Comfortable filming a real item and checking program eligibility.',pro=pro,con=con,inputs='Three real buyer questions, five alternative offers with source links, and one first-user test.',sample=demo,recipe=recipe,check=check,channels=['Relevant Facebook Groups','Instagram','Search + marketplace reviews'],prompt=f'Help me build and test {name} for {buyer}. Confirmed research: [sources and questions]. Required contents: {contents}. First ask for missing facts. Create the smallest complete version, a filled fictional example, a blank reusable version and clear first-use instructions. Do not copy competitors or invent demand, sales, statistics or endorsements. Give a five-minute first task and a test checklist. For affiliate products instead create a real-item inspection and demo plan, never a fake product review.',tags=tags,paid='Optional design or AI subscription only after a useful free prototype. Storefront fees, payout access and product sample costs are separate.',kind=kind,source=source,evidence=evidence,contents=contents))
product('project-kit','Freelancer project-start kit','New freelancers struggling to collect clear client instructions','A printable workbook plus editable project and delivery checklist.','6–10 hours','You can make and test it without code. A filled example makes it useful immediately.','There are many free alternatives. Focus on one task, not a giant “business system”.','A quick start, client-question sheet, scope page, task tracker, delivery email and filled example.',[
 'Open the included Freelancer Project Starter to see a complete example. Pick one buyer, such as a new freelance designer.',
 'Ask three freelancers what goes wrong when a project starts. Note the words they use and the free tools they already have.',
 'Open Google Docs → Blank document. Make Start here, Questions to ask, Agreed work, My tasks and Delivery pages. Write original wording.',
 'Fill one fictional project from start to finish. Add a blank copy of each useful page. Test with someone unfamiliar with it.',
 'Export PDF and an editable copy link with safe permissions. Check both in a private browser window. Offer a preview before a paid launch.'
], 'A tester can write agreed work, deadlines and a delivery message without asking what a heading means.', 'Fill one vague client request into a clear project checklist.', 'https://www.notion.com/templates/category/freelance','Notion has an established freelance template category, including client and project tools. This confirms the format and competition, not demand for your specific kit.', ['organize','words','short'])
product('job-tracker','Job-application tracker','Applicants juggling several roles and follow-up dates','A Sheet for roles, links, application dates, next steps and interview notes.','5–9 hours','A small, practical task with an easy screen demonstration.','Free trackers are common. It does not improve hiring outcomes by itself.','Application table, status dropdowns, follow-up reminders guide and three fictional filled rows.',[
 'Ask three applicants how they track roles now and what they forget. Do not ask them to share private applications.',
 'Open Sheets → Blank. Add Company, Role, Link, Applied date, Status, Next action, Next date and Notes.',
 'Use Data → Data validation for Saved, Applied, Interview, Rejected and Closed. Freeze row one and enable a filter.',
 'Add three fictional example rows on an Example tab and a blank Tracker tab. Write a Start here tab explaining dates and statuses.',
 'Test sorting by Next date and changing status. Give the buyer a copy link, not editing access to your master.'
], 'A tester can add a role, filter active applications and find the next action. No job or interview guarantee.', 'Add a fictional application and show the next follow-up date.', 'https://www.notion.com/templates/category/job-search','Notion’s job-search category contains existing application and career tools. The starting angle is organization, not a claim that templates get jobs.', ['organize','research','short'])
product('content-planner','Small-business content planner','A shop owner or solo professional planning next week’s posts','A seven-day Sheet and reusable question-to-post worksheet.','5–9 hours','A visible blank-to-plan result. Can serve several business types.','Generic caption bundles are easy to replace. Teach a repeatable planning step.','Reader questions, seven-day plan, caption checks, source log and filled shop example.',[
 'Choose one buyer type, such as a photographer or maker. Collect five questions they repeatedly answer.',
 'In Sheets create Day, Question, Topic, Caption draft, Image, Next action and Approved columns.',
 'Write a one-page rule: answer one question per post, use verified facts and choose one next step.',
 'Fill one seven-day fictional example. Add a blank week and a caption check page. Ask a potential buyer to plan three posts.',
 'Export instructions as PDF and share a template-copy link. Test all links from a new browser session.'
], 'The buyer produces three distinct post ideas, not seven generic “buy now” captions.', 'Turn three customer questions into three useful posts.', 'https://www.notion.com/templates/category/social-media','Notion lists social media planners and calendars. Many free alternatives make a clear buyer-specific first task essential.', ['words','organize','short'])
product('media-kit','Creator media-kit template','Small creators who need to explain their work to potential partners','An original two-page media-kit layout and a guide to filling it honestly.','6–10 hours','Strong visual preview and a clear reason to use it.','Creators need real stats and samples. A polished file does not guarantee sponsorships.','Profile, audience, verified stats with dates, sample work, services and contact section.',[
 'Ask two creators what a partner usually requests. List only information they can actually provide.',
 'In Canva choose a blank A4 document or Slides layout. Build your own two-page design using free assets.',
 'Page one: who I help, what I create, real audience information and sample links. Page two: services, process and contact.',
 'Add fictional example values labeled DEMO. Leave buyer fields clearly marked in the template. Don’t invent testimonials.',
 'Check Canva’s current template licensing. Deliver an editable template link only for assets you may include, plus a PDF guide.'
], 'Stats have dates, demo values are labeled, samples open and the editable link makes a buyer copy.', 'Replace demo creator details with a verified profile and sample link.', 'https://www.canva.com/create/media-kits/','Canva supports media kits and explains their use. This is evidence of a known format, not sponsorship demand or sales volume.', ['visual','media','short'])
product('budget-sheet','Simple monthly expense sheet','People who want to see where everyday spending goes','A manual income and expense Sheet with a category summary.','6–10 hours','Easy to demonstrate using fictional numbers. No bank connection needed.','Formula mistakes damage trust. Avoid financial or investment promises.','Transactions tab, category list, month summary, formula tests and filled example.',[
 'Ask potential users which categories they need. Keep the first version manual and in one currency.',
 'In Sheets add Date, Description, Type, Category and Amount. Use dropdowns for Income/Expense and simple categories.',
 'Name the first tab Transactions. On a Summary tab, put Income, Expenses and Remaining in A2:A4. In B2 use =SUMIF(Transactions!C2:C,"Income",Transactions!E2:E). In B3 use =SUMIF(Transactions!C2:C,"Expense",Transactions!E2:E). In B4 use =B2-B3. If your locale needs semicolons, replace formula commas. Test five fictional entries and hand-calculate totals.',
 'Make an Example copy and a blank buyer copy. Protect formula cells where possible and explain how to add a row.',
 'Test a zero-spend month, a negative adjustment and a new category. Export instructions. Do not ask for bank login details.'
], 'Hand totals equal formula totals, currency is clear and adding a row does not silently break the summary.', 'Add three fictional expenses and show the correct total.', 'https://www.notion.com/templates/category/personal-finance','Notion offers budgets and expense trackers. The curated scope is a simple recording tool, not financial guidance.', ['organize','build','patient'])
product('event-planner','Small-event planning pack','People arranging a birthday, workshop or small wedding','A timeline, task list, supplier comparison and cost sheet.','6–10 hours','A concrete planning problem and clear printable pages.','Event requirements vary. Don’t pretend one template covers every legal or venue requirement.','Planning timeline, tasks, cost table, supplier notes and a fictional 20-person workshop example.',[
 'Choose one event type you understand. Ask three organizers which task they nearly missed.',
 'In Docs create Start here, Timeline, Tasks, Suppliers and Day-of checklist pages.',
 'In Sheets add Item, Estimated cost, Agreed cost, Paid and Due date. Label every currency.',
 'Fill a fictional 20-person workshop example with clearly illustrative dates and amounts. Add a blank version.',
 'Ask a tester to plan the first three actions. Edit anything they cannot explain. Deliver PDF and editable copies.'
], 'The buyer can find the next task and unpaid cost. Example dates cannot be mistaken for their actual event.', 'Turn an event date into three dated planning tasks.', 'https://www.notion.com/templates/category/event-planning','Notion’s event category provides planning templates. We narrowed the idea to a small event because a complete first version is easier to test.', ['organize','words','patient'])
product('study-planner','Weekly study and assignment planner','Students trying to organize deadlines and realistic study blocks','A reusable weekly plan plus assignment tracker and a filled example.','5–9 hours','A practical task with no technical setup.','Students already have free alternatives. Don’t promise grades or admissions.','Deadline list, available-time sheet, weekly plan, review page and fictional exam-week example.',[
 'Ask students what they miss: deadlines, time estimates or review sessions. Choose one problem.',
 'Create a Sheet with Subject, Task, Due date, Estimated minutes, Next action and Status.',
 'Create a weekly grid with realistic available blocks and breaks. Show how to place urgent tasks first.',
 'Fill a fictional week. Add a blank week and a five-minute setup guide. Do not schedule impossible workloads.',
 'Test with someone who has three tasks and limited time. Deliver printable PDF plus editable copy.'
], 'A tester can fit tasks into available time and spot a missed deadline. No learning or grade guarantee.', 'Fit three tasks into a fictional student’s available week.', 'https://www.notion.com/templates/category/study-planner','Notion has a dedicated study-planner category. This establishes the format and competition, not willingness to pay for another generic planner.', ['organize','words','short'])
product('craft-affiliate','Craft stencils and beginner supplies','Hobby makers looking for a visible simple project','Recommend one inspected stencil or craft-supply set through an eligible affiliate program.','4–8 hours after sample arrives','You can film the actual process and final craft.','Materials cost money. Skill and surface compatibility vary.','One real product, approved affiliate link, checked materials and a demonstration.',[
 'Open the program available in your country. Verify acceptance, commission, eligible payout method and content rules before planning a sale.',
 'Search the exact set on the seller page. Read recent reviews about missing pieces, size and surface compatibility. Compare three alternatives.',
 'Obtain a real sample you can afford. Count pieces and try the stencil on a suitable practice surface.',
 'Film materials → applying stencil → result → limitation. Use your real footage and label the affiliate relationship.',
 'Attach only an approved product link. Track clicks, confirmed commissions, returns and available payout separately.'
], 'The real product matches the link, the demo shows what it did, and commission and payout eligibility are verified.', 'Show one stencil turning a plain practice card into a finished design.', 'https://www.shopify.com/blog/trending-products','Shopify includes arts and crafting materials in its US merchant category research. Our stencil subcategory is an editorial demo-friendly pick, not a measured bestseller.', ['visual','media','patient'],'affiliate')
product('bedding-affiliate','Pillowcases and simple bedding','Shoppers checking fabric, size and care before buying','Recommend one real pillowcase set through an eligible affiliate program.','4–8 hours after sample arrives','Fit, texture and package contents are easy to show.','You cannot prove sleep or health benefits. Shipping, returns and sample cost affect the choice.','Actual sample, dimensions, label facts, care instructions and approved link.',[
 'Confirm your country and creator account qualify for a program. Do not rely on US TikTok Shop rules if you live elsewhere.',
 'Compare three sets by verified size, fabric label, package contents, seller returns and recent reviews.',
 'Obtain one sample. Measure it and show it fitting a pillow of the stated size. Read the care label on camera.',
 'Film package contents, fit, texture and one limitation. Do not claim it fixes sleep, skin or health.',
 'Disclose the affiliate link. Track actual completed commission and settlement, not projected earnings from views.'
], 'Size, fabric and contents match the product. No medical, sleep or invented comfort guarantee.', 'Show the size label, fitting a pillow and actual package contents.', 'https://www.shopify.com/blog/trending-products','Shopify identifies bedding as an established category. Pillowcases are a smaller demonstration scope. The research does not establish demand for a particular seller’s set.', ['visual','media','short'],'affiliate')
product('phone-affiliate','Phone stands and mounts','Creators or desk workers checking whether a stand fits their setup','Recommend one real phone stand with a checked fit and stability demonstration.','4–8 hours after sample arrives','A clear hands-on test and visible use case.','Compatibility matters. Do not film unsafe driving or invent durability tests.','Real stand, phone dimensions, supported size, setup instructions and approved link.',[
 'Check affiliate program eligibility and payout access for your country. If unavailable, choose a download or offer editing as a service.',
 'Compare three stands using the seller specs and recent fit/stability reviews. Avoid unverified charging or safety claims.',
 'Obtain a sample. Test your actual phone, case, portrait/landscape orientation and desk surface.',
 'Film unboxing, fit, setup and one limitation. Keep the phone visible in the final shot so viewers can judge the result.',
 'Attach an approved link with disclosure. Track actual orders/commission and returns. Never buy your own item to manufacture proof.'
], 'You show the actual compatible device and limitations. Product link, disclosure and commission terms are correct.', 'Place a real phone into the stand and show the exact fit.', 'https://www.shopify.com/blog/trending-products','Shopify discusses phone mounts within growing dashboard accessories. A desk stand is our narrower, safer-to-film starting idea. That is an inference, not evidence of desk-stand sales growth.', ['visual','media','build'],'affiliate')
assert len(SERVICES)==10 and len(PRODUCTS)==10
CHOICES={'service':SERVICES,'product':PRODUCTS}
