import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './fixture.mjs';
import {onRequest as choice} from '../functions/api/choice.js';
import {onRequest as track} from '../functions/api/track.js';
import {onRequest as checklist} from '../functions/api/journal/checklist.js';
import {onRequest as sheets} from '../functions/api/journal/sheets.js';
import {onRequest as middleware} from '../functions/_middleware.js';
import {onRequestGet as profile} from '../functions/api/profile.js';
import {onRequestPost as progress} from '../functions/api/progress.js';
import {capacity,diagnose,csvText} from '../js/logic.js';
test('track choices persist atomically and reject invalid or unauthenticated changes',async()=>{const {db,context}=setup();assert.equal((await track(context('/api/track',undefined,''))).status,401);assert.equal((await track(context('/api/track',{track:'invalid'}))).status,400);assert.equal((await track(context('/api/track',{track:'service'}))).status,200);assert.deepEqual(await (await track(context('/api/track'))).json(),{track:'service'});assert.equal((await track(context('/api/track',{track:'product'}))).status,409);await track(context('/api/track',{track:'product',reset:true,confirm:'CLEAR_MY_WORK',expectedTrack:'service'}));assert.equal((await (await track(context('/api/track'))).json()).track,'product');assert.equal(db.prepare('SELECT SUM(done) as n FROM progress').get().n,1);assert.equal((await progress(context('/api/progress',{module:'selected-track-service',done:true}))).status,400);});
test('guide sync preserves IDs, completed work, notes and custom tasks and is idempotent',async()=>{const {db,context}=setup();db.exec("INSERT INTO checklist_tasks VALUES('old','u1','track-b','old title','old detail',0,1,'Keep this note',0,CURRENT_TIMESTAMP);INSERT INTO checklist_tasks VALUES('custom','u1','track-b','My extra task','custom details',1,1,'Keep custom',1,CURRENT_TIMESTAMP);");await checklist(context('/api/journal/checklist?track=track-b'));await checklist(context('/api/journal/checklist',{action:'generate',track:'track-b'}));await checklist(context('/api/journal/checklist',{action:'generate',track:'track-b'}));const old=db.prepare("SELECT * FROM checklist_tasks WHERE id='old'").get();assert.equal(old.done,1);assert.equal(old.note,'Keep this note');assert.match(old.title,/sample of your selected service/);assert.equal(db.prepare('SELECT COUNT(*) as n FROM checklist_tasks').get().n,11);assert.equal(db.prepare("SELECT note FROM checklist_tasks WHERE id='custom'").get().note,'Keep custom');assert.equal((await checklist(context('/api/journal/checklist?track=bad'))).status,400);assert.equal((await checklist(context('/api/journal/checklist',{action:'delete',id:'old'}))).status,403);});
test('task ownership, custom addition and note saving',async()=>{const {db,context}=setup();await checklist(context('/api/journal/checklist?track=track-a'));const id=db.prepare('SELECT id FROM checklist_tasks LIMIT 1').get().id;await checklist(context('/api/journal/checklist',{action:'note',id,note:'A saved brief'}));await checklist(context('/api/journal/checklist',{action:'toggle',id,done:true}));assert.equal(db.prepare('SELECT note FROM checklist_tasks WHERE id=?').get(id).note,'A saved brief');await checklist(context('/api/journal/checklist',{action:'add',track:'track-a',title:'Preview checkout'}));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM checklist_tasks').get().n,11);assert.equal((await checklist(context('/api/journal/checklist',{action:'add',track:'wrong',title:'x'}))).status,400);db.exec("INSERT INTO checklist_tasks VALUES('other','u2','track-a','private','',0,0,'private',1,CURRENT_TIMESTAMP)");await checklist(context('/api/journal/checklist',{action:'note',id:'other',note:'attack'}));assert.equal(db.prepare("SELECT note FROM checklist_tasks WHERE id='other'").get().note,'private');});
test('sheets keep existing data and start with blank observations, dates and unknown metrics',async()=>{const {context}=setup();for(const type of ['outreach','daily','weekly']){const data=await (await sheets(context('/api/journal/sheets?type='+type))).json();assert.ok(data.rows.length);if(type==='outreach')assert.equal(data.rows[0]['Signal Noticed'],'');if(type==='daily'){assert.equal(data.rows[0].Date,'');assert.equal(data.rows[0].Views,'');}await sheets(context('/api/journal/sheets',{type,row_idx:0,data:{...data.rows[0],Notes:'Keep row'}}));const reread=await (await sheets(context('/api/journal/sheets?type='+type))).json();assert.equal(reread.rows[0].Notes,'Keep row');}assert.equal((await sheets(context('/api/journal/sheets?type=bad'))).status,400);});
test('paid documents remain authenticated; only actual static asset extensions are public',async()=>{const {context}=setup();for(const path of ['/index.html','/playbooks/playbook-f-content-service.html','/prompts.html','/assets/samples/content-delivery.html','/curriculum/vault.json','/assets/samples/lead-replies.txt','/index.html.js/secret'])assert.equal((await middleware(context(path,undefined,''))).status,302,path);assert.equal((await middleware(context('/assets/workbench.css',undefined,''))).status,200);assert.equal((await middleware(context('/preview.html',undefined,''))).status,200);assert.equal((await middleware(context('/preview',undefined,''))).status,200);assert.equal((await middleware(context('/index.html'))).status,200);const c=context('/api/track',{track:'service'});c.request=new Request(c.request,{headers:{Cookie:'__session=valid; csrf_token=token','Content-Type':'application/json'}});assert.equal((await middleware(c)).status,403);});
test('profile excludes selection metadata from completion',async()=>{const {context}=setup();await track(context('/api/track',{track:'service'}));await progress(context('/api/progress',{module:'playbook-f-step-1',done:true}));const d=await (await profile(context('/api/profile'))).json();assert.equal(d.progress.done,1);assert.equal(d.progress.total,52);assert.equal(d.progress.pct,2);});
test('diagnostic ties are explicit; capacity arithmetic and CSV escaping are correct',()=>{assert.equal(diagnose(['service','product']),null);assert.equal(diagnose(['product','product','service']),'product');assert.deepEqual(capacity({credits:1000,cost:10,attempts:3,shots:2,extra:0,price:20}),{perEdit:60,edits:16,perEditCost:1.25});assert.equal(capacity({credits:1000,cost:0,attempts:3,shots:2,extra:0,price:20}),null);assert.equal(capacity({credits:1,cost:10,attempts:1,shots:1,extra:0,price:20}).perEditCost,null);assert.equal(csvText(['x'],[{x:'hello,"friend"'}]),'"x"\r\n"hello,""friend"""');});

test('confirmed route reset clears only this member’s work and keeps account access',async()=>{
 const {db,context,env}=setup();await track(context('/api/track',{track:'service'}));
 await choice(context('/api/choice',{track:'service',choice:'website'}));await checklist(context('/api/journal/checklist?track=track-b'));await sheets(context('/api/journal/sheets?type=outreach'));
 db.exec("UPDATE checklist_tasks SET done=1,note='old note' WHERE user_id='u1'; INSERT INTO progress(user_id,module,done) VALUES('u1','playbook-f-step-1',1),('u2','playbook-a-step-1',1); INSERT INTO checklist_tasks VALUES('other','u2','track-a','private','',0,1,'private note',1,CURRENT_TIMESTAMP); INSERT INTO sheets VALUES('other-sheet','u2','outreach','private'); INSERT INTO sheet_rows(id,sheet_id,row_idx,data) VALUES('other-row','other-sheet',0,'private'); INSERT INTO sheet_settings(id,user_id,sheet_type,column_order,column_widths) VALUES('other-settings','u2','outreach','[]','{}');");
 assert.equal((await track(context('/api/track',{track:'product',reset:true}))).status,400);
 assert.equal((await track(context('/api/track',{track:'product',reset:true,confirm:'CLEAR_MY_WORK',expectedTrack:'product'}))).status,409);
 const r=await track(context('/api/track',{track:'product',reset:true,confirm:'CLEAR_MY_WORK',expectedTrack:'service'}));assert.equal(r.status,200);
 for(const t of ['checklist_tasks','sheets','sheet_settings'])assert.equal(db.prepare('SELECT COUNT(*) AS n FROM '+t+" WHERE user_id='u1'").get().n,0,t);
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM sheet_rows').get().n,1);
 assert.deepEqual(await(await choice(context('/api/choice'))).json(),{track:'product',choice:null});
 assert.equal(db.prepare("SELECT SUM(done) AS n FROM progress WHERE user_id='u1'").get().n,1);
 assert.equal(db.prepare("SELECT note FROM checklist_tasks WHERE id='other'").get().note,'private note');
 assert.equal(db.prepare("SELECT data FROM sheet_rows WHERE id='other-row'").get().data,'private');
 assert.equal(db.prepare("SELECT COUNT(*) AS n FROM users WHERE id='u1'").get().n,1);assert.equal(await env.SESSIONS.get('sess:valid'),'u1');
 const fresh=await(await checklist(context('/api/journal/checklist?track=track-a'))).json();assert.ok(fresh.tasks.every(r=>!r.done&&!r.note));assert.deepEqual(fresh.tasks[0].guide,{letter:'B',step:1});
});
test('route reset rolls back all deletions if saving the new route fails',async()=>{
 const {db,context}=setup();await track(context('/api/track',{track:'service'}));await checklist(context('/api/journal/checklist?track=track-b'));await sheets(context('/api/journal/sheets?type=outreach'));
 db.exec("UPDATE checklist_tasks SET note='keep'; CREATE TRIGGER fail_reset BEFORE INSERT ON progress WHEN NEW.module='selected-track-product' BEGIN SELECT RAISE(ABORT,'test failure'); END;");
 await assert.rejects(()=>track(context('/api/track',{track:'product',reset:true,confirm:'CLEAR_MY_WORK',expectedTrack:'service'})));
 assert.equal((await(await track(context('/api/track'))).json()).track,'service');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM checklist_tasks').get().n,10);assert.equal(db.prepare('SELECT note FROM checklist_tasks LIMIT 1').get().note,'keep');assert.ok(db.prepare('SELECT COUNT(*) AS n FROM sheet_rows').get().n>0);
});
test('offer choices are authenticated, route-bound and do not erase completed work',async()=>{
 const {db,context}=setup();assert.equal((await choice(context('/api/choice',undefined,''))).status,401);assert.equal((await choice(context('/api/choice'))).status,409);await track(context('/api/track',{track:'service'}));
 assert.equal((await choice(context('/api/choice',{track:'product',choice:'website'}))).status,409);assert.equal((await choice(context('/api/choice',{track:'service',choice:'not-a-service'}))).status,400);
 await choice(context('/api/choice',{track:'service',choice:'website'}));await progress(context('/api/progress',{module:'playbook-f-step-1',done:true}));await choice(context('/api/choice',{track:'service',choice:'custom'}));
 assert.equal((await(await choice(context('/api/choice'))).json()).choice,'custom');assert.equal(db.prepare("SELECT done FROM progress WHERE module='playbook-f-step-1'").get().done,1);
 assert.equal((await progress(context('/api/progress',{module:'selected-choice-service-copy',done:true}))).status,400);assert.equal((await(await profile(context('/api/profile'))).json()).progress.done,1);
});
test('affiliate choices show eligibility and real-item tasks rather than download-building tasks',async()=>{
 const {context}=setup();await track(context('/api/track',{track:'product'}));await choice(context('/api/choice',{track:'product',choice:'phone-affiliate'}));
 const r=await(await checklist(context('/api/journal/checklist?track=track-a'))).json();assert.equal(r.tasks.length,10);assert.match(r.tasks[0].detail,/J\./);assert.deepEqual(r.tasks[0].guide,{letter:'J',step:1});assert.match(r.tasks[2].title,/real sample/);assert.ok(r.tasks.every(t=>!t.detail.startsWith('B.')));
 await choice(context('/api/choice',{track:'product',choice:'project-kit'}));const d=await(await checklist(context('/api/journal/checklist?track=track-a'))).json();assert.match(d.tasks[0].detail,/B\./);
});
