"""Build the guided Blueprint from reviewable curriculum, using only Python stdlib."""
import sys, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from curriculum.books import BOOKS
from curriculum.vault_review import review
from layout import E, hero, write, chapter, flow
from samples import build_samples, EXAMPLES
BOOKS.sort(key=lambda b:b['letter'])
BY={b['letter']:b for b in BOOKS}
build_samples()

# One screen, one decision. A saved member gets the route rather than onboarding again.
start='''<section class="start-stage" data-start-new hidden><span class="eyebrow">Welcome to your Blueprint / start here</span><h1>First, choose<br>your track.</h1><p class="lede">You don’t need ten ideas at once. Find the kind of work you can do, then build one useful thing you can offer.</p><div class="start-teaser"><div><h2>A starting point that fits you.</h2><p>Six short questions. We’ll save your track and show the first practical step.</p></div><a class="button" href="/quiz.html">Get my track <span aria-hidden="true">↗</span></a></div><div class="start-caption"><span>SERVICES OR PRODUCTS</span><span>FREE TOOL ROUTES INCLUDED</span></div></section><section class="start-stage" data-start-saved hidden><span class="eyebrow">Your track is saved</span><h1 data-route-heading>Continue your Blueprint.</h1><p class="lede" data-route-description></p><div class="start-teaser"><div><h2>Pick up the next step.</h2><p>Open the task you’re working on, with its guide and output check.</p></div><a class="button" href="/checklist.html">My next steps ↗</a></div></section><p class="status" data-track-status role="status">Opening your Blueprint…</p><div class="start-note">Your track sets the starting sequence. The <a href="/playbooks.html">full playbook library</a> stays available in the sidebar.</div>'''
write('index.html','Start here',start,'start')

# Six decisions shown gradually; no preselected answers or predicted earnings.
questions=[('What would you prefer to sell?','A useful download people can reuse.','A defined project for one client.'),('What can you demonstrate this week?','A template, planner or guide for a problem I understand.','A content, copy or video sample for a business.'),('How do you prefer to find buyers?','Publish useful demonstrations and learn from potential buyers.','Research suitable buyers and have direct conversations.'),('What type of work suits you?','Build once, improve from feedback and support buyers.','Adapt each deliverable to a client’s brief.'),('What evidence do you have?','People repeatedly ask me about a specific problem.','I can spot and improve a specific business deliverable.'),('What can you finish with the time you have?','A small reusable product and a test with likely buyers.','A tightly scoped service sample and a few researched pitches.')]
qs=''.join(f'<fieldset class="quiz-question" data-question="{i}"'+(' hidden' if i else '')+f'><legend>{E(q)}</legend><label><input type="radio" name="q{i}" value="product" required>{E(a)}</label><label><input type="radio" name="q{i}" value="service" required>{E(b)}</label></fieldset>' for i,(q,a,b) in enumerate(questions))
quiz=hero('Find your starting track','Let’s make one good decision.','Choose the answer closest to what you can actually do. This guides your first task; it does not predict income.')+f'''<div class="quiz-body"><div class="quiz-progress"><span id="quiz-position">QUESTION 01 / 06</span><progress id="quiz-progress" max="6" value="1" aria-label="Question progress"></progress></div><form id="track-quiz" novalidate>{qs}<div class="quiz-nav"><button type="button" class="secondary" id="quiz-back" disabled>← Back</button><button type="button" id="quiz-next" disabled>Next question →</button></div></form><section class="track-panel" id="quiz-result" hidden aria-live="polite"></section><p class="status" id="quiz-status" role="status"></p><p class="quiz-hint">You can revisit your track in Profile & track settings. Your saved work stays with you.</p></div>'''
write('quiz.html','Get my track',quiz,'start')

# Track-specific progression. The full checklist lives under an intentional disclosure.
journey=hero('Your working route','Your next steps.','Follow the sequence for your track. Keep your notes beside the work.')+'''<div data-no-track hidden><div class="start-teaser"><div><h2>Choose your starting point first.</h2><p>Get a track so your next task and relevant guides can appear here.</p></div><a class="button" href="/quiz.html">Get my track ↗</a></div></div><div data-journey hidden><div class="route-summary"><span class="eyebrow">Selected track / saved to your account</span><h2 data-route-heading></h2><p class="lede" data-route-description></p></div><section class="next-action" id="next-task" hidden aria-live="polite"></section>'''+f'<div data-route-map="service" hidden>{flow("service")}</div><div data-route-map="product" hidden>{flow("product")}</div>'+'''<details class="quiet-details" id="tasks"><summary>View my full task list & saved notes</summary><div><label class="muted" for="task-track">Saved list</label><select id="task-track"><option value="track-b">Services · Track B</option><option value="track-a">Products · Track A</option><option value="30-day-blueprint">Setup & launch</option></select><p class="status" id="tasks-status" role="status"></p><progress id="task-progress" max="100" value="0" aria-label="Task completion"></progress><div id="task-list"></div><form id="add-task" class="search-row"><input name="title" required maxlength="160" placeholder="Add a personal task" aria-label="New task title"><button>Add task</button></form><button class="secondary" id="refresh-tasks">Refresh guide wording, keep my notes</button></div></details><details class="quiet-details"><summary>See the guides connected to my track</summary><div data-related-books></div></details><p class="route-settings">Need a different starting point? <a href="/profile.html#track-settings">Review or change my track</a>.</p></div><p class="status" data-track-status role="status">Opening your saved track…</p>'''
write('checklist.html','My next steps',journey,'journey')

write('playbooks.html','Playbooks',hero('Ten connected guides','Open the guide for the work in front of you.','Your selected track filters this library. Shared guides appear on both routes; you can explore the full library any time.')+'<div class="section-head"><span class="muted">Every guide includes an output, a prompt and a pass check.</span><label class="muted">Showing <select id="book-filter"><option value="all">All playbooks</option><option value="service">My service route</option><option value="product">My product route</option></select></label></div><div class="chapter-list">'+''.join(chapter(b) for b in BOOKS)+'</div>','books')

# A chapter reader, not a wall of boxes. Direct step links still work.
for b in BOOKS:
 sections=''
 toc='<a href="#route" data-reader-link><span>Start / </span>Tool route</a>'
 free=''.join(f'<p>{E(x)}</p>' for x in b['free'])
 paid=''.join(f'<p>{E(x)}</p>' for x in b['paid'])
 sections+=f'''<section id="route" class="reader-section" data-reader-section><span class="eyebrow">Before you begin</span><h2>Start with the tools you have.</h2><p class="lede">The output stays the same. Choose how you’ll produce it.</p><div class="route-controls" role="group" aria-label="Tool route"><button data-route="free" aria-pressed="true">Free tools</button><button data-route="paid" aria-pressed="false">Optional paid tools</button></div><div class="route-block" data-route-content="free"><h3>Free workflow</h3>{free}</div><div class="route-block" data-route-content="paid" hidden><h3>Paid workflow</h3>{paid}<p>Check the current plan and your actual bottleneck before spending.</p></div><a href="/tools.html">Compare tools & credit costs ↗</a></section>'''
 for i,s in enumerate(b['steps'],1):
  toc+=f'<a href="#step-{i}" data-reader-link>{i:02} <span>/ {E(s["title"])}</span></a>'
  key=f'playbook-{b["letter"].lower()}-step-{i}'
  resource='<p class="muted"><a href="/assets/samples/client-intake.csv" download>Blank client brief (CSV) ↓</a> · Use with the filled reference in the Example chapter.</p>' if b['letter']=='F' and i==1 else ''
  sections+=f'''<section class="reader-section step" id="step-{i}" data-reader-section hidden><div class="step-head"><span class="number">{i:02}</span><div><h2>{E(s['title'])}</h2><p>{E(s['action'])}</p></div></div>{resource}<div class="output"><b>Produce this</b>{E(s['output'])}<div class="pass-check"><b>Pass check</b>{E(s['check'])}</div></div><div class="prompt"><span class="eyebrow">Your working prompt</span><pre>{E(s['prompt'])}</pre><button data-copy>Copy prompt</button></div><label class="task-top"><input type="checkbox" data-progress="{key}">I produced the output and checked it.</label></section>'''
 ex=b['example'];toc+='<a href="#example" data-reader-link>Example</a><a href="#next" data-reader-link>What’s next</a>'
 sections+=f'''<section id="example" class="reader-section" data-reader-section hidden><span class="eyebrow">Finished reference / fictional practice inputs</span><h2>{E(ex['title'])}</h2><p>{E(ex['body'])}</p><div class="actions"><a class="button" href="/assets/samples/{ex['asset']}">Inspect the example ↗</a><a href="/assets/samples/{ex['asset']}" download>Download ↓</a></div><p class="muted">Examples demonstrate deliverables and arithmetic. Use your own verified inputs.</p></section><section id="next" class="reader-section" data-reader-section hidden><span class="eyebrow">Use what you made</span><h2>The next useful move.</h2><p>Choose the guide that fits your finished output.</p>{''.join(chapter(BY[x]) for x in b['next'])}<details class="quiet-details"><summary>When you get stuck</summary><div>{''.join(f'<details class="quiet-details"><summary>{E(q)}</summary><div><p>{E(a)}</p></div></details>' for q,a in b['fixes'])}</div></details><div class="actions"><a href="/checklist.html">Return to my next steps ↗</a></div></section>'''
 body=hero(f'Playbook {b["letter"]} / {b["track"] if b["track"]!="both" else "both tracks"}',b['title'],b['goal'])+f'''<div class="book-layout"><nav class="toc" aria-label="Playbook chapters"><span class="eyebrow">Your sequence</span>{toc}</nav><div class="reader" data-reader><div class="reader-meter"><span id="reader-position">START / TOOL ROUTE</span><progress id="reader-progress" max="{len(b['steps'])}" value="0" aria-label="Saved playbook steps"></progress></div>{sections}<div class="reader-pager"><button class="secondary" id="reader-back" disabled>← Previous</button><button id="reader-next">Start step 01 →</button></div><p class="book-footnote">Completion checks save to your account. Moving between chapters does not mark a step complete.</p></div></div>'''
 write(b['path'],'Playbook '+b['letter'],body,'books')

pack=[dict(book=b['letter'],title=s['title'],t=s['prompt'],check=s['check']) for b in BOOKS for s in b['steps'][:5]]
assert len(pack)==50
promptrows=''
for i,p in enumerate(pack,1):
 promptrows+=f'''<article class="prompt" data-prompt-item data-category="{p['book']}"><details><summary><div><span class="tag">{i:02} / 50 · Playbook {p['book']}</span><h3>{E(p['title'])}</h3></div></summary><pre>{E(p['t'])}</pre><p class="muted">Check: {E(p['check'])}</p><button data-copy>Copy prompt</button> <a href="/{BY[p['book']]['path']}">Open the workflow ↗</a></details></article>'''
opts=''.join(f'<option value="{b["letter"]}">{b["letter"]}. {E(b["title"])}</option>' for b in BOOKS)
write('prompts.html','50 action prompts',hero('Your working prompt pack','Find the task. Copy the prompt.','Five focused prompts per playbook. Replace the brackets with verified facts, then use the pass check to review what AI produces.')+f'<div class="actions"><button data-download-prompts>Download all 50 ↓</button><a href="/vault.html">300-prompt reference vault ↗</a></div><div class="search-row"><input id="prompt-search" type="search" aria-label="Search prompts" placeholder="Search by task or output"><select id="prompt-filter" aria-label="Filter by playbook"><option value="all">All playbooks</option>{opts}</select></div><p class="status" id="prompt-count" aria-live="polite">50 prompts</p><div class="prompt-grid">{promptrows}</div><p id="prompt-empty" class="empty" hidden>No matches. Try a shorter phrase.</p>','prompts')

vault=[review(p) for p in json.loads((ROOT/'curriculum/vault.json').read_text())]
guard='Use only supplied facts or explicitly linked verified evidence. Never invent clients, testimonials, usage experience, results, scarcity, guarantees or statistics. Use placeholders for missing facts. Honor consent, copyright, platform eligibility and actual offer terms. Do not claim guaranteed earnings or virality.'
for p in vault:
 if p['title']=='Cold DM — the reply-getter':p['t']=pack[3]['t']
 if any(x in p['title'].lower() for x in ['testimonial','social proof','social-proof']):p['t']='Using only supplied, permission-approved proof [exact quotes, verified results, authorized logos], write '+p['title'].lower()+' for [offer] and [audience]. Keep quotes faithful. If no approved proof is supplied, create a clearly labeled demonstration instead.'
 if 'guarantee' in p['title'].lower():p['t']='Draft a revision/refund policy for [offer] using approved terms [terms]. State eligibility, time limit, exclusions and help route. Do not offer an income/performance guarantee. Flag missing terms.'
 p['t']+='\n\n'+guard
vc=''.join(f'<article class="prompt" data-prompt-item data-category="{E(p["cat"])}"><details><summary><div><span class="tag">{i+1:03} · {E(p["cat"])}</span><h3>{E(p["title"])}</h3></div></summary><pre>{E(p["t"])}</pre><button data-copy>Copy prompt</button></details></article>' for i,p in enumerate(vault))
vo=''.join(f'<option value="{x}">{x.title()}</option>' for x in sorted({p['cat'] for p in vault}))
write('vault.html','Reference vault',hero('300 reference prompts','Choose a task, then a variation.','For the guided sequence, start with the 50 action prompts. Use this reference library for variations and always review the output.')+f'<div class="search-row"><input id="prompt-search" type="search" aria-label="Search reference prompts" placeholder="Search the vault"><select id="prompt-filter" aria-label="Filter category"><option value="all">All categories</option>{vo}</select></div><p class="status" id="prompt-count" aria-live="polite">300 prompts</p><div class="prompt-grid">{vc}</div><p id="prompt-empty" class="empty" hidden>No matches.</p>','prompts')

# Trackers are an operating resource, not onboarding content.
write('trackers.html','My trackers',hero('Your operating sheets','Record what actually happened.','Keep buyer observations, content actions and collected revenue separate. Existing rows stay in your account.')+'''<div class="search-row"><select id="sheet-type" aria-label="Tracking sheet"><option value="outreach">Outreach tracker</option><option value="daily">Content tracker</option><option value="weekly">Weekly scorecard</option></select><button class="secondary" id="sheet-export">Export CSV ↓</button><button class="secondary" id="sheet-add">Add row</button></div><p class="status" id="sheet-status" role="status"></p><div class="table-wrap" id="sheet-table"></div><p class="muted">Edit a cell, then leave it to save. Review old practice prefills before treating them as actual observations. Collected gross revenue, profit and available payouts are different measurements.</p>''','sheets')

write('examples.html','Worked examples',hero('Inspect the finished work','A reference for the output you’re making.','The Blueprint is for people building an online income route. These varied fictional examples show how to produce and hand off the work; they do not choose your niche.')+'''<div class="chapter-list"><article class="chapter"><span class="chapter-number">01</span><div><span class="eyebrow">Service reference / three client types</span><h3><a href="/assets/samples/content-delivery.html">From client brief to complete content pack.</a></h3><p>Fitness coach, repair business and online shop. Each has a brief, calendar, seven captions, three layouts, QA and a handoff.</p></div><a class="chapter-arrow" href="/assets/samples/content-delivery.html" aria-label="Open content delivery">↗</a></article><article class="chapter"><span class="chapter-number">02</span><div><span class="eyebrow">Product reference / reusable workbook</span><h3><a href="/assets/samples/freelancer-project-starter.html">A small product with a usable first task.</a></h3><p>Freelancer brief, filled copy-project example, scope worksheet, asset checklist, approval message and review log.</p></div><a class="chapter-arrow" href="/assets/samples/freelancer-project-starter.html" aria-label="Open product reference">↗</a></article></div><details class="quiet-details"><summary>More production references</summary><div><p><a href="/assets/samples/copy-project.txt">Hero and three follow-up emails ↓</a></p><p><a href="/assets/samples/video-storyboard.csv">Product video storyboard ↓</a></p><p><a href="/assets/samples/carousel-storyboard.txt">Carousel storyboard ↓</a></p><p><a href="/assets/samples/affiliate-checklist.txt">Affiliate eligibility worksheet ↓</a></p></div></details>''','examples')

TOOLS=json.loads((ROOT/'curriculum/tools.json').read_text())
tools=''
for name,domain,use,free,paid,url in TOOLS:
 tools+=f'<article class="tool-row"><div class="tool-head"><span class="brand">{E(name[0])}<img src="https://www.google.com/s2/favicons?domain={domain}&amp;sz=64" alt="{E(name)} icon" loading="lazy" data-brand-image></span><h3>{E(name)}</h3></div><div><span class="eyebrow">{E(use)}</span><p>{E(free)}</p><details><summary>Paid options & limitations</summary><p>{E(paid)}</p></details><a href="{E(url)}" target="_blank" rel="noopener">Official details ↗</a></div></article>'
fields=[('plan-cost','Monthly plan cost in your currency',0),('credits','Credits available',1000),('attempt-cost','Credits per attempt',10),('attempts','Attempts per accepted shot',3),('shots','Generated shots per edit',2),('extra','Other credits per edit',0)]
ff=''.join(f'<label>{E(label)}<input id="{key}" type="number" min="0" step="any" value="{value}" required></label>' for key,label,value in fields)
write('tools.html','Tools & costs',hero('Free first / checked 6 October 2026','Use the smallest stack that delivers.','One writing tool, one editor, one delivery method. Upgrade when you can name the bottleneck. A subscription does not create demand.')+f'<div class="tool-list">{tools}</div><section class="section" id="calculator"><span class="eyebrow">Plan your actual production budget</span><h2>Estimate usable video edits.</h2><p>The starting inputs are hypothetical, not a Higgsfield subscription. Enter your displayed model cost, expected retries and shots per finished edit. Real capacity may be lower.</p><form id="credit-calculator"><div class="field-grid">{ff}</div><div class="output" id="credit-result" aria-live="polite"></div></form><details class="quiet-details"><summary>How the estimate works</summary><div><p>Credits per edit = attempt cost × attempts × generated shots + other credits. Edits = floor(available credits ÷ credits per edit). Subscription cost per estimated edit = plan cost ÷ edits. Labor, taxes and separate plans are excluded.</p></div></details></section>','tools')

sources=json.loads((ROOT/'curriculum/sources.json').read_text())
write('sources.html','Source notes',hero('Editorial review / 6 October 2026','Check before spending or publishing.','Prices, features, credits and eligibility change. Your current account and the official plan take priority.')+'<section class="section"><table><thead><tr><th>Primary source</th><th>What to check</th></tr></thead><tbody>'+''.join(f'<tr><td><a href="{E(url)}" target="_blank" rel="noopener">{E(name)}</a></td><td>{E(note)}</td></tr>' for name,url,note in sources)+'</tbody></table></section><section class="section"><h2>How to read the examples.</h2><p>Names, business facts and arithmetic in worked examples are fictional practice inputs. They show deliverables, not customer results or expected earnings.</p><p>No fixed number of posts, messages or days guarantees a sale. Track actual interest, purchases, costs and available payouts separately.</p><p>No universal Instagram carousel boost is claimed. Use the format to teach a clear step and compare your own buyer actions.</p></section>','tools')

profile=hero('Account & preferences','Your Blueprint, your starting point.','Manage your profile and revisit your route here.')+'''<div class="profile-form"><div class="profile-hero"><div class="avatar-wrap"><svg viewBox="0 0 84 84"><circle class="bg" cx="42" cy="42" r="36"/><circle class="fg" id="profileProgress" cx="42" cy="42" r="36" stroke-dasharray="226.19" stroke-dashoffset="226.19"/></svg><img id="avatarImg" src="/assets/brands/avatar.svg" alt="Your assigned avatar"></div><div class="profile-meta"><h2 id="displayName">My profile</h2><p id="displayEmail"></p><p id="memberSince"></p></div></div><div class="field"><label for="nameInput">Display name</label><input id="nameInput" type="text" maxlength="40" placeholder="Your name"></div><div class="field"><label for="emailInput">Account email</label><input id="emailInput" type="text" disabled></div><img id="avatarPreview" src="/assets/brands/avatar.svg" alt="" hidden><div class="actions"><button id="saveNameBtn">Save name</button><button class="secondary" id="refreshBtn">Refresh</button></div><p id="saveMsg" class="status" role="status"></p><section class="section"><h2>Playbook progress</h2><div class="progress-row"><div class="progress-track"><div class="progress-fill" id="progressFill"></div></div><span id="progressLabel">0%</span></div><p id="progressText" class="muted"></p><p class="muted">Saved playbook steps. Task-list completion is shown separately in My next steps.</p></section><section class="section" id="track-settings"><span class="eyebrow">Track settings</span><h2 data-route-heading>Choose a starting track</h2><p data-route-description>Run the quiz to match a practical route to your preferences.</p><a class="button secondary" href="/quiz.html">Review or change my track ↗</a><p class="muted">Switching keeps your existing notes, tasks and completed playbook steps.</p><p class="status" data-track-status role="status"></p></section><section class="section"><h2>Session</h2><button class="secondary" id="logoutBtn">Log out</button></section></div>'''
write('profile.html','Profile & track settings',profile,'profile','<script src="/js/profile.js?v=20261006-sidebar"></script>')

# Public, signed-out preview with several contexts and a useful independent lesson.
preview=hero('Free preview / fictional practice inputs','A useful output starts with better inputs.','This same process works across different business types: confirm the facts, answer a reader’s question, edit the draft, and package a clear next step.')+'<section class="section"><span class="eyebrow">01 / Compare the inputs</span><h2>The buyer changes. The process stays useful.</h2><div class="chapter-list">'+''.join(f'<article class="chapter"><span class="chapter-number">{i:02}</span><div><h3>{E(d["label"])}</h3><p>{E(d["audience"])}. Offer: {E(d["offer"])}.</p></div></article>' for i,d in enumerate(EXAMPLES,1))+'</div></section><section class="section"><span class="eyebrow">02 / Fix the draft</span><h2>Make the claim match the brief.</h2>'+''.join(f'<details class="quiet-details"'+(' open' if i==0 else '')+f'><summary>{E(d["label"])} / raw → edited</summary><div class="before-after"><div><span class="eyebrow">Raw draft</span><p>{E(d["raw"])}</p></div><div class="after"><span class="eyebrow">Edited from confirmed facts</span><p>{E(d["edited"])}</p></div></div></details>' for i,d in enumerate(EXAMPLES))+'</section><section class="section"><span class="eyebrow">03 / Try it yourself</span><h2>Write one better caption.</h2><ol><li>Choose a business or product you understand.</li><li>Write its reader, actual offer, approved facts and next step.</li><li>Answer one reader question in a short caption.</li><li>Remove claims the facts do not support. Check the final link.</li></ol><p class="notice">These are fictional demonstrations, not commissioned work or earnings stories.</p></section><section class="section"><h2>What the complete Blueprint adds.</h2><p>A saved starting track, ten connected playbooks, full delivery and product examples, free/paid tool routes, 50 action prompts, 300 reference prompts, and saved tasks and trackers.</p><p>Use the seller’s current listing for price, purchase and access terms. Existing members can sign in below.</p><a class="button" href="/login.html">Member sign-in ↗</a></section>'
(ROOT/'preview.html').write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Free preview | AI Income Blueprint</title><link rel="stylesheet" href="/assets/workbench.css?v=20261006-sidebar2"></head><body><main class="public-content"><div class="public-brand">AI Income Blueprint / preview</div>{preview}<footer class="footer">Build useful work. Examples show the process, not guaranteed income.</footer></main></body></html>')
print(f'Built a sidebar-led Blueprint, six-step onboarding, {len(BOOKS)} guided readers, {len(pack)} action and {len(vault)} reference prompts.')
