"""Specific examples and optional deep instructions for the shared readers."""
from layout import E,write,hero
from curriculum.choices import CHOICES,SERVICES,PRODUCTS

def steps(items):return '<ol class="action-steps">'+''.join(f'<li>{E(x)}</li>' for x in items)+'</ol>'
def prompt(title,text):return f'<details class="quiet-details"><summary>{E(title)}</summary><div class="prompt"><pre>{E(text)}</pre><button data-copy>Copy prompt</button></div></details>'
def recipe(c):return ('<p><a href="/assets/samples/website-starter.txt" download>Complete static website starter ↓</a> · Rename a copy to index.html.</p>' if c['id']=='website' else '')+steps(c['recipe'])+f'<p class="pass-check"><b>Check your finished work</b>{E(c["check"])}</p>'
def choice_options(track='both'):
 return '<option value="custom">My own offer / general steps</option>'+''.join(f'<optgroup label="{label}">'+''.join(f'<option value="{c["id"]}">{E(c["name"])}</option>' for c in CHOICES[t])+'</optgroup>' for t,label in [('service','Services'),('product','Products')] if track in ['both',t])
def context_selector(track):
 return f'<div class="offer-context"><label for="offer-example">Show examples for</label><select id="offer-example" data-context-choice>{choice_options(track)}</select><small>This changes the examples on this page. <a href="/choose.html">Change my saved offer</a>.</small><p class="status" data-choice-status role="status"></p></div>'

def adaptation(b,i):
 letter=b['letter'];cs=[c for t in CHOICES for c in CHOICES[t] if b['track'] in [t,'both']]
 cards=[]
 for c in cs:
  isservice=c['kind']=='service';affiliate=c['kind']=='affiliate'
  if letter=='A':
   content={1:f'<p><b>What to sell:</b> {E(c["sell"])}</p><p><b>Who to try:</b> {E(c["buyer"])}</p><p>Pick one of these buyer types for the first batch. The sample and search should use the same type.</p>',2:f'<p>For {E(c["name"].lower())}, start with {E(", ".join(c["channels"]))}. Look for people who need these outputs: {E(c["sell"])}</p><p>Record what you saw, not what you assume about their budget. Use the channel instructions below.</p>',3:f'<p><b>A useful small sample:</b> {E(c["sample"])}</p>'+recipe(c)+prompt('Prompt for this service',c['prompt']),4:f'<p>Ask to share this: {E(c["sample"])}</p><p>Example structure: “Hi [name], I saw [checked detail] on [page/post]. I made a small {E(c["name"].lower())} demo that addresses it. Would you like to see it?” Replace the brackets and check the tone before sending.</p>',5:f'<p>Ask about these inputs: {E(c["inputs"])}</p><p>Then confirm the number of files, deadline, approver and what they want changed.</p>',6:f'<p>Starter scope: {E(c["sell"])}</p><p>Include the required inputs: {E(c["inputs"])}</p><p>Finish with this check: {E(c["check"])}</p>'}[i]
  elif letter=='F':
   content={1:f'<p><b>Request these:</b> {E(c["inputs"])}</p><p><b>Agreed output:</b> {E(c["sell"])}</p>',2:recipe(c)+prompt('Creation prompt for this service',c['prompt']),3:f'<p>Use the first piece as your quality reference. Complete this exact package: {E(c["sell"])}</p>'+steps(['Keep the approved facts beside the file while working.','Name each final file by purpose, not final-final2.','Compare the finished file list with the agreement and ask about missing inputs.']),4:f'<p>{E(c["check"])}</p>'+steps(['Open the file or link as someone without your editing access.','Run the actual task using fictional or authorized test data.','Record the result and fix any broken step.']),5:f'<p>Deliver {E(c["sell"].lower())}</p>'+steps(['Create Final exports and Editable originals folders.','Add a Start here note explaining each file and the first action.','Check access from a private browser window, then send the link and agreed revision instructions.']),6:f'<p>Ask: “Does this {E(c["name"].lower())} match the agreed work? Please send any changes covered by our revision round in one list.”</p><p>After approval, ask separately whether you may show the work. Silence is not permission.</p>'}[i]
  elif letter=='B':
   if affiliate:content='<p>This is a physical-product affiliate choice. You do not need to create a download. Open <a href="/playbooks/playbook-j-affiliate-product-demo.html" target="_blank" rel="noopener">J: Check eligibility and demonstrate an item ↗</a>. Use C and E for content after your real-item inspection.</p>'+f'<p>{E(c["evidence"])}</p>'
   else:content={1:f'<p><b>Buyer:</b> {E(c["buyer"])}</p><p><b>First task:</b> {E(c["sample"])}</p><p>{E(c["evidence"])}</p><p>Ask “How do you do this now?”, “Where does it get confusing?” and “Would you try this small preview?” Record their actual answers.</p>',2:f'<p><b>Required contents:</b> {E(c["contents"])}</p><p>Write a Start here page that explains the first task: {E(c["sample"])}</p>',3:recipe(c)+prompt('Creation prompt for this product',c['prompt']),4:f'<p>Compare five alternatives for {E(c["name"].lower())}. Include free options. Your price is a test, not a fact proved by this guide.</p><p>Check file access and payout eligibility before a launch. Use the storefront setup instructions below.</p>',5:f'<p><b>Show this task working:</b> {E(c["sample"])}</p><p><b>List these contents:</b> {E(c["contents"])}</p><p><b>Be clear about the limit:</b> {E(c["con"])}</p>'}[i]
  elif letter=='C':
   content=f'<p><b>Your visible result:</b> {E(c["sample"])}</p>'+steps(['Open the finished output or real item first. Capture a clear payoff shot.','Record the starting problem, one making/use action and the final check.','Say why the step matters in one short sentence. Invite the viewer to the relevant sample, preview or disclosed item link.'])
  elif letter=='E':content=f'<p>Use this filled example on slide five: {E(c["sample"])}</p><p>Use this on slide six: {E(c["check"])}</p><p>The reader is {E(c["buyer"].lower())}. Write the lesson for them, then give one relevant next step.</p>'
  elif letter=='G':content=f'<p><b>Exact offer:</b> {E(c["sell"])}</p><p><b>Reader:</b> {E(c["buyer"])}</p><p><b>Limit to explain:</b> {E(c["con"])}</p><p>Use these facts in the prompt. For client copy work, replace them with the client’s approved facts.</p>'
  elif letter=='H':content=f'<p>The real evidence is {E(c["sample"].lower())}</p><p>Show that first. A generated background or stock insert can add context, but cannot prove this work was used by a paying customer.</p><p>{E(c["paid"])}</p>'
  elif letter=='I':content=f'<p><b>Preview to send:</b> {E(c["sample"])}</p><p><b>Explain what the full offer adds:</b> {E(c["sell"])}</p><p>Ask which part of this task they need help with. Answer using the real file or inspected item.</p>'
  elif letter=='J':content=recipe(c)+f'<p><b>Research note:</b> {E(c["evidence"])}</p>' if affiliate else '<p>You selected a download. Skip affiliate eligibility and physical samples. Use B to make the download, C/E to demonstrate it and I to answer buyer questions.</p>'
  else:content=f'<p><b>Keep the work bounded:</b> {E(c["sell"])}</p><p><b>Tradeoff to watch:</b> {E(c["con"])}</p><p>Track making, checking, revisions, support and actual costs separately.</p>'
  link=f'/assets/samples/{c["id"]}-example.txt' if isservice else f'/assets/samples/{c["id"]}-starter.csv'
  content+=f'<p><a href="{link}" download>Inspect the filled practice file ↓</a> · <a href="{E(c["source"])}" target="_blank" rel="noopener">Why this choice was included ↗</a></p>'
  cards.append(f'<div data-choice-content="{c["id"]}" hidden><span class="eyebrow">Example for your offer</span><h3>{E(c["name"])}</h3>{content}</div>')
 return '<div class="specific-example">'+''.join(cards)+'<div data-choice-content="custom"><h3>Using your own offer?</h3><p>Follow the main steps above. Use the closest example in the selector as a reference. You don’t have to enter a name to choose your own offer. Before selling, write the exact output, required facts and one check. Ask the working prompt to clarify anything you do not know.</p></div></div>'

CHANNELS=[
 ('Instagram','https://www.instagram.com/',[
 'Tap Search and enter a buyer phrase such as “photographer Bristol”, “online tutor” or “handmade stationery”. Try a service keyword and a location separately.',
 'Open relevant profiles, their bio link and recent posts. Read captions and comments for questions the business answers or an explicit request for help.',
 'For copy, inspect the bio, offer and enquiry page. For design, inspect readability. For video, find authorized longer videos that could become clips. For research, use only public business information.',
 'Record the profile/post URL, date and exact observation. If the account is private or evidence is inaccessible, do not claim you checked it.',
 'Use a relevant business DM if allowed. Ask permission to share a small sample. Do not mass-message followers or scrape personal details.'
 ],'Instagram profiles and public posts. Use profile/post URLs. Check the bio, offer link and visible questions. Do not guess post dates, treat low follower count as buying intent, scrape followers or access private profiles.'),
 ('Facebook Groups','https://www.facebook.com/groups/',[
 'Search a buyer phrase such as “small business owners”, “freelance designers” or a local business group. Open Groups in the search results.',
 'Read About and group rules before joining or posting. Some groups prohibit promotion or unsolicited messages.',
 'Use the group’s search for real requests: “website help”, “looking for an editor”, “product descriptions” or the task your service solves.',
 'Save the permitted post URL and what the author actually asked. Answer a useful part of their question publicly where rules allow.',
 'Ask whether they want a sample only when relevant and permitted. Do not export members or DM everyone in the group.'
 ],'Permitted public Facebook posts and group requests. Quote only the relevant request, record the post URL/date and respect the group’s rules. Mark login-only or inaccessible posts unverified. Do not harvest members or send messages.'),
 ('LinkedIn','https://www.linkedin.com/',[
 'Search a buyer role or business type, then review Companies, People or Posts as relevant to the offer.',
 'Try task phrases such as “need a presentation”, “looking for a video editor” or “new website”. Check the person’s actual business role.',
 'Open their company page or public website and confirm one relevant need. A job title alone is not proof they want a service.',
 'Record the post/company URL, checked date, observed task and permitted business contact route.',
 'Write a short manual connection or message where your account and platform rules permit. Do not pretend you have met them.'
 ],'Public LinkedIn company pages and posts. Verify the business role and actual request. Separate a visible request from a suggested fit. No inferred budget, scraped personal emails or automatic outreach.'),
 ('Google Maps and websites','https://maps.google.com/',[
 'For location-based services, search a buyer type and city, such as “photographer Leeds” or “repair service Austin”. Remote buyers may be better found elsewhere.',
 'Open the listing and its official website. Check what a customer sees, such as a missing enquiry link, unclear service description or an outdated page.',
 'Check the observation directly. Don’t call someone’s website “bad”. Identify one specific improvement you can show.',
 'Record business name, official page URL, date and the public business contact route. Do not guess owner names or private contacts.',
 'Offer a small demo by an appropriate permitted message or call. Build a fictional niche demo first, then personalize only from verified facts.'
 ],'Google Maps listings and official websites for [city or region]. Confirm the actual business and visible page issue. Use public business contacts only. No claims that a quiet listing proves budget, interest or a missing website unless checked.'),
 ('Marketplaces and creator websites','https://www.upwork.com/',[
 'Search live requests for your task on a marketplace that accepts your location, or search creator/shop websites for a public business enquiry address.',
 'Read the exact scope, deadline, budget if stated and submission rules. Do not move a marketplace conversation outside the platform if prohibited.',
 'Choose work you can demonstrate. Match one sample to the request and explain the relevant change, not every service you could offer.',
 'Record the request URL, date, required output and unanswered questions. A posted budget is a source fact. A budget you guessed is unknown.',
 'Submit through the allowed route. Marketplace fees, credits and identity requirements can add costs. Check them before applying.'
 ],'Live marketplace requests or official creator/shop business pages. Follow each platform’s application rules. Use only stated budgets and public business contacts. Do not bypass platform fees or message people outside a required platform.'),
]
def research_channels():
 out='<section class="deep-guide"><h3>Choose where to look</h3><p>You can find suitable clients on any relevant platform. Start with one channel and one buyer type. These are search methods, not promises of ready buyers.</p>'
 for name,url,actions,scope in CHANNELS:
  t=f'Research-agent task for {name}. My service: [service]. Exact package: [files]. Buyer type: [type]. Location: [city/country or remote]. Search constraints: {scope} Find up to ten relevant businesses or explicit requests. Return name, source URL, checked date, exact visible observation, potential help, permitted public business contact route and unknowns. Separate verified facts from suggested fit. Do not invent contacts, dates, budgets, buyer intent or metrics. Do not send anything. If a source cannot be opened, say so and give manual search phrases instead. Start with three rows for my review before continuing.'
  out+=f'<details class="quiet-details"><summary>{E(name)} / exact search steps</summary><div><a href="{url}" target="_blank" rel="noopener">Open {E(name)} ↗</a>{steps(actions)}{prompt("Copy the "+name+" research prompt",t)}</div></details>'
 out+='<h3>Turn what you know into a better agent prompt</h3>'+steps(['Copy the main working prompt on this step into ChatGPT, Claude or Z.ai. Fill what you know and write “unknown” for the rest.','Answer its short questions. Ask it to give one final research prompt for your chosen channel.','Open Manus or Z.ai, start a new chat/task and paste the final prompt. If web/search tools are available in your account, enable them. Otherwise paste public source text or search manually.','Ask for three rows first. Open their links and check the facts before asking for more. Copy checked rows into My trackers.'])
 out+='<p><a href="https://manus.im/" target="_blank" rel="noopener">Open Manus ↗</a> · <a href="https://chat.z.ai/" target="_blank" rel="noopener">Open Z.ai / GLM ↗</a> · <a href="/tools.html">Compare limits and cost</a></p><p>Manus’s free Agent mode has limited credits. Its parallel Wide Research feature is currently paid. No free 20-hour research run is promised. Z.ai chat and its paid developer API are different products. Check which tools your chat actually offers.</p></section>'
 return out

def messaging():
 return '<section class="deep-guide"><h3>Match the message to the channel</h3>'+steps(['Instagram: “Hi [name], your [checked post/page] gave me an idea for [specific sample]. Would you like to see it?”','Facebook Group: answer the posted question first. Example: “You can make that page clearer by showing [specific step]. I made a small demo. If group rules allow, would you like the link?”','LinkedIn or email: state the relevant business task, one checked observation and the small sample. Use an accurate subject such as “One idea for your enquiry page”.','Phone: “Hi, I’m [name]. Is now a bad time for a quick question? I noticed [specific checked detail] on your public page and made a small demo. May I email it to the right person?” Do not pretend to be an existing supplier.'])+calling()+'</section>'
def calling():
 return '''<details class="quiet-details"><summary>Optional phone calls / US, Europe and Africa</summary><div><p>Calling can cost money. Free alternatives are permitted manual Instagram messages, helpful group replies and relevant business conversations. Choose the route that fits your location and the recipient.</p><table><thead><tr><th>Where you are</th><th>Practical starting option</th></tr></thead><tbody><tr><td>United States</td><td>Check your local SIM/carrier plan first. Google Voice has US personal and paid standalone options. Business plans and international calls have separate terms. Don’t assume an unlimited domestic plan includes every destination.</td></tr><tr><td>Europe</td><td>Use your local carrier’s business/international rates, or an eligible Google Voice Workspace plan in a supported country. Not every European country is supported. Compare a prepaid international app for the exact destination.</td></tr><tr><td>Africa</td><td>Start with a local SIM/carrier and check its international tariff. Talk360 offers prepaid international calling. Confirm app availability, payment method and the exact origin/destination rate before topping up. It does not promise a US caller ID or a free calling plan.</td></tr></tbody></table><ol class="action-steps"><li>Open the provider’s rate page and choose your calling country and the recipient’s country. Check mobile versus landline, currency, minimum top-up and expiry.</li><li>Estimate cost as rate × planned minutes, plus any subscription or connection charge shown. Example arithmetic only: 0.10 per minute × 30 minutes = 3.00 in that rate’s currency.</li><li>Check business use and recipient-country calling rules, respect local hours and stop when asked. Do not record calls without checking consent requirements.</li><li>Use your real identity and approved caller ID. Don’t hide your location or claim to be a local office.</li></ol><p><a href="https://support.google.com/voice/answer/9249103?hl=en" target="_blank" rel="noopener">Google Voice plans and country scope ↗</a> · <a href="https://www.talk360.com/rates" target="_blank" rel="noopener">Talk360 live rates ↗</a> · <a href="https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule" target="_blank" rel="noopener">US calling rules ↗</a> · <a href="https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-pecr/electronic-and-telephone-marketing/telephone-marketing/" target="_blank" rel="noopener">UK calling rules ↗</a></p></div></details>'''

def storefront():return '''<section class="deep-guide"><h3>Set up delivery without custom coding</h3><ol class="action-steps"><li>Open a supported storefront’s current signup and payout information. Confirm your country, identity requirements, fees and available withdrawal method first.</li><li>For Gumroad: open your dashboard → Products → New product → choose the suitable digital-product type → name and price → add your finished content files. Use the current official help if labels differ.</li><li>Write the description, add a clear preview and state required software, support and actual refund terms. Check whether the buyer needs a PDF, editable copy link or both.</li><li>Use the platform’s test-purchase flow to check the receipt and content access. Open every delivered file and link as a buyer. A test order is not earnings proof.</li><li>Publish only after the real files and delivery work. For a physical store, use Shopify or another supported commerce platform. Product records, checkout, shipping, tax and orders need a working store, not a static AI page.</li></ol><p><a href="https://gumroad.com/help/article/149-adding-a-product" target="_blank" rel="noopener">Gumroad product setup ↗</a> · <a href="https://gumroad.com/help/article/62-testing-a-purchase" target="_blank" rel="noopener">Gumroad test purchase ↗</a> · <a href="https://help.shopify.com/en/manual/products/add-update-products" target="_blank" rel="noopener">Shopify product setup ↗</a></p></section>'''

def video_recipe():return '<section class="deep-guide"><h3>A complete 30-second demonstration</h3>'+steps(['0–3 seconds: show the finished result. Say “Here is [specific output]”. Keep the file or item readable.','3–7 seconds: show the starting problem. Say why this one step matters to the buyer.','7–18 seconds: show two real actions. Film the click, edit, filled field or product use while you explain it. Cut waiting time.','18–25 seconds: show the human check. Correct one line, tap the link, check the total or test the fit.','25–30 seconds: show the final output and one next action. Example: “The preview shows this first task. Open it from my profile.” Use only a link/path that actually exists.'])+prompt('Prompt to turn your actual work into a shot list','I made/tested [actual output] for [buyer task]. These are the exact actions I took [steps]. Turn this into a 30-second demonstration with five shots: result, starting problem, two making/use actions, check and next step. Give timestamps, exact screen/hand action, spoken line, short text and filename. Ask about unknown facts first. No invented buyer, revenue or product performance. Keep the total voiceover short enough to read naturally.')+'</section>'

def extras(b,i):
 if b['letter']=='A' and i==2:return research_channels()
 if b['letter']=='A' and i==4:return messaging()
 if b['letter']=='B' and i==4:return storefront()
 if b['letter']=='C' and i in [1,2]:return video_recipe()
 if b['letter']=='J' and i==1:return '<p><a href="https://seller-us.tiktok.com/university/essay?knowledge_id=6939143037667118" target="_blank" rel="noopener">Current US TikTok Shop creator policy ↗</a> · Other markets have different rules. Use your market’s official Academy and your account’s actual eligibility screen.</p>'
 return ''
