"""Finished, varied practice deliverables. No one niche is the product's audience."""
from pathlib import Path
import csv
from layout import E, hero, write
ROOT=Path(__file__).resolve().parents[1]
A=ROOT/'assets/samples'
EXAMPLES=[
 dict(key='coach',label='Fitness coach',name='Move With Sam',audience='Beginners considering their first coached session',offer='An introductory movement session; no medical or transformation claims',facts='Tuesday and Thursday, 17:00–19:00; adult beginners; owner confirms suitability and fees',cta='Ask about an introductory session at [approved inquiry link]',raw='Transform your body fast with the best coach. Only two spaces left!',edited='New to coached sessions? Tell us what you want to work on and ask how an introductory session runs. We explain the format and confirm whether it suits you before agreeing a booking.',questions=['What happens in the first session?','What should I ask before booking?','Which goals should I share?','How does an inquiry become a booking?','When are sessions offered?','What information do you need?','What should I review next week?'],answers=['We discuss your goals, explain the session format and answer your questions before agreeing the next step.','Ask about the format, accessibility, fees and anything the coach needs to know before attending.','Describe the activity you want support with and your current experience. Avoid treating a general post as personal health advice.','Send your question, preferred day and relevant session needs. The coach confirms details and suitability first.','Practice session times are Tuesday and Thursday, 17:00–19:00. Ask about actual availability before making plans.','Your goal, preferred time and questions about the format are enough to start an inquiry. Sensitive health details need an agreed private channel.','Look at the questions people actually asked. Plan one clear answer for the next post; do not invent progress stories.']),
 dict(key='repair',label='Repair business',name='ClearFix Repairs',audience='People deciding whether to request a device assessment',offer='Device assessment and a written quote before approved repair work',facts='Monday–Friday, 09:00–17:00; phone and laptop assessments; price and timing confirmed after assessment',cta='Request an assessment at [approved inquiry link]',raw='We fix every device instantly at the lowest price. Book before prices go up!',edited='Not sure whether your device needs a repair? Describe the issue and the device model when requesting an assessment. We explain the assessment process and confirm a quote before any repair work is agreed.',questions=['What happens at an assessment?','What details should I send?','Will I know the repair cost first?','What should I ask about device data?','When can I request an assessment?','How do I approve the next step?','What happens after the work?'],answers=['We review the reported issue and explain the assessment process. Repair scope, price and timing are confirmed before approved work begins.','Share the device model, what happens and when you first noticed it. Do not send passwords in public messages.','Ask for the assessment terms and a written quote. This practice fact sheet does not include fixed prices or a promise every device can be repaired.','Ask the business about data handling and backup instructions before handing over a device. Never assume a repair automatically protects every file.','Practice opening hours are Monday–Friday, 09:00–17:00. Confirm the assessment appointment and any fee before traveling.','Review the written findings, scope, price and expected timing. Agree the work explicitly before it proceeds.','Check the agreed repair and ask about the actual support terms. Record your own observations; avoid inventing satisfaction claims.']),
 dict(key='shop',label='Online shop',name='DeskKind',audience='People comparing compact desk storage options',offer='A three-compartment desk organizer',facts='Practice dimensions: 20 × 10 × 8 cm; three compartments; intended for pens and small notes; delivery terms confirmed on product page',cta='See dimensions and delivery details at [approved product link]',raw='The organizer that doubles productivity overnight. Everyone loves it!',edited='Need a place for pens and small notes? This three-compartment organizer measures 20 × 10 × 8 cm in our practice fact sheet. Check the dimensions against your desk space and review the product page before ordering.',questions=['Will it fit my desk?','What can I store?','How do the compartments work?','What should I check before ordering?','Where do I see delivery terms?','Who is this useful for?','What should the next post answer?'],answers=['Practice dimensions are 20 × 10 × 8 cm. Measure the space you plan to use before ordering.','The brief names pens and small notes. Show those items in a real product demonstration; do not invent weight or storage-capacity claims.','Show each of the three compartments with the actual product. Illustrative scenes should not change its shape or make unsupported promises.','Confirm dimensions, material details, price, delivery and refund terms on the approved product page. Unknown details remain questions for the owner.','Read the current product-page terms for your location. This practice example does not promise a delivery date or free shipping.','It may suit someone organizing pens and small notes in a compact space. Show the size so the viewer can decide rather than claiming universal suitability.','Use real buyer questions about size, storage or delivery. Demonstrate one answer with the actual product instead of inventing reviews.'])
]

def table(headers,rows):
 return '<div class="table-wrap"><table><thead><tr>'+''.join(f'<th>{E(x)}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{E(x)}</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

def build_samples():
 A.mkdir(exist_ok=True)
 with (A/'client-intake.csv').open('w') as f:
  w=csv.writer(f,lineterminator='\n');w.writerow(['Field','Client-approved answer','Confirmed by / date'])
  w.writerows((field,'','') for field in ['Business and reader','Offer and approved facts','Price and promotion rules','Hours / availability to verify','Final inquiry or product link','Voice and prohibited claims','Assets and image permissions','Deliverables and exclusions','Posting owner / reply owner','Approval contact','Due date and revision agreement'])
 selector='<div class="sample-selector"><label for="example-select">Choose another fictional business</label><select id="example-select">'+''.join(f'<option value="{d["key"]}">{d["label"]} · {d["name"]}</option>' for d in EXAMPLES)+'</select><p class="muted">These made-up businesses show one weekly-post service. You are not selling to these businesses. Pick the example you understand best.</p></div>'
 sections=''
 for n,d in enumerate(EXAMPLES):
  designs=''
  titles=['ASK A CLEAR QUESTION','SHOW THE USEFUL DETAILS','MAKE THE NEXT STEP EASY']
  subtitles=['What does the reader need to know?','Use facts from approved client facts','One relevant action, no pressure']
  for i,(title,sub) in enumerate(zip(titles,subtitles),1):
   colors=[('#7133d7','#faf9f6'),('#ebe5f3','#322342'),('#26212d','#f2eafb')];bg,fg=colors[i-1]
   words=title.split();lines=[' '.join(words[:2]),' '.join(words[2:])]
   svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1350" role="img" aria-label="{E(title)}"><rect width="1080" height="1350" fill="{bg}"/><text x="88" y="125" font-family="sans-serif" font-size="27" letter-spacing="3" fill="{fg}">{E(d["name"].upper())} / PRACTICE</text><path d="M88 225h904" stroke="{fg}"/><g fill="{fg}" font-family="sans-serif" font-size="82" font-weight="bold"><text x="88" y="520">{E(lines[0])}</text><text x="88" y="625">{E(lines[1])}</text></g><text x="88" y="965" fill="{fg}" font-family="sans-serif" font-size="30">{E(sub)}</text><text x="88" y="1170" fill="{fg}" font-family="sans-serif" font-size="28">Replace the practice details before publishing ↗</text></svg>'
   filename=f'{d["key"]}-layout-{i}.svg';(A/filename).write_text(svg)
   designs+=f'<div><img src="/assets/samples/{filename}" alt="{E(d["label"])} layout {i}: {E(title)}"><a href="/assets/samples/{filename}" download>Editable SVG {i} ↓</a></div>'
  calendar=[(f'Day {i+1}',q,['FAQ graphic','Own photo + caption','Detail card'][i%3],'Pending approval') for i,q in enumerate(d['questions'])]
  captions=''.join(f'<section class="section"><span class="eyebrow">Caption {i+1:02} · {E(calendar[i][2])}</span><h3>{E(q)}</h3><p>{E(answer)}</p><p><b>{E(d["cta"])}</b></p></section>' for i,(q,answer) in enumerate(zip(d['questions'],d['answers'])))
  briefs={'Practice business':d['name'],'Reader':d['audience'],'Offer':d['offer'],'Confirmed practice facts':d['facts'],'Next action':d['cta'],'Assets & rights':'Owner-approved photos or clearly illustrative licensed imagery. Obtain permission for identifiable people.','Agreed work':'Seven captions, three editable layouts, calendar, one revision round and handoff.','Excluded':'Publishing, account access, ads and guaranteed sales or leads.'}
  brief='<dl class="brief-grid">'+''.join(f'<dt>{E(k)}</dt><dd>{E(v)}</dd>' for k,v in briefs.items())+'</dl>'
  handoff=f'Hi {d["name"]} team, your seven-post content pack is ready at [folder link]. Open 01-client-facts, then 02-calendar. Each numbered caption matches its design reference. Please confirm every fact, replace the inquiry/product link and approve image permissions before publishing. Send the single agreed revision round as one list by [agreed date]. Posting and replies remain with your team. Please reply approved or return the change list.'
  sections+=f'<article class="example-sheet" data-example="{d["key"]}"'+(' hidden' if n else '')+f'><span class="eyebrow">{E(d["label"])} / filled delivery</span><h2>{E(d["name"])}: from client facts to final files.</h2><h3>01 / Check the client facts first</h3>{brief}<h3>02 / Plan what each post will explain</h3>{table(["Day","Reader question","Visual","Approval"],calendar)}<h3>03 / Edit the draft</h3><div class="before-after"><div><span class="eyebrow">Raw AI draft</span><p>{E(d["raw"])}</p><p class="muted">Unsupported claims and urgency. Do not publish.</p></div><div class="after"><span class="eyebrow">Edited from confirmed facts</span><p>{E(d["edited"])}</p></div></div><h3>04 / Seven finished captions</h3>{captions}<h3>05 / Three editable layout references</h3><p>1080 × 1350 SVGs. Replace practice names and words with the caption topic. Open in a compatible editor or recreate the hierarchy in Canva using free elements. Export numbered PNGs and preview on a phone.</p><div class="designs">{designs}</div><h3>06 / Check and package</h3><ul><li>Every fact agrees with the approved brief.</li><li>Every photo and audio asset has the right permission.</li><li>No performance guarantee, invented proof or leftover placeholder goes live.</li><li>The actual link opens the agreed next step.</li><li>The calendar, caption numbering and design files match.</li><li>The owner knows who publishes, how to approve and how to request the revision.</li></ul><p>Folders: 01-client-facts / 02-calendar / 03-captions / 04-designs / 05-instructions.</p><h3>07 / Delivery message</h3><p>{E(handoff)}</p><h3>08 / Revision and reporting</h3>{table(["File","Requested correction","Owner-approved fact"],[("05-caption.txt","[specific wording change]","[confirmed replacement]")])}<p>Delivery: seven captions and three designs. Approval: pending. Publishing, reach, inquiries and sales: not measured. Ask what the owner could use without help; record actual metrics only when available.</p></article>'
  with (A/f'{d["key"]}-calendar.csv').open('w') as f:
   w=csv.writer(f,lineterminator='\n');w.writerow(['Day','Reader question','Visual','Caption','Next action','Approval']);w.writerows((f'Day {i+1}',q,calendar[i][2],answer,d['cta'],'Pending') for i,(q,answer) in enumerate(zip(d['questions'],d['answers'])))
 body=hero('Three contexts · one repeatable process','What a weekly-post client receives.','This page shows one finished weekly-post package. The business names are made up. Read the client facts, captions, images and delivery message to see what you would send. This is one service example, not the only service you can sell.')+selector+sections+'<div class="actions no-print"><button data-print>Print this example / save PDF</button><a href="/playbooks/playbook-f-content-service.html">Follow the delivery playbook ↗</a></div>'
 write('assets/samples/content-delivery.html','Content delivery reference',body,'examples')
 fields=['Client, reader and intended action','Approved offer, facts and proof','Deliverables, exclusions and required inputs','Dates, price, payment and revision agreement','Files, approval owner and final next step']
 product=hero('Product reference · complete printable workbook','Freelancer Project Starter.','Organize one small client project from client instructions to approval. This is a fictional prototype you can inspect, not a promise of clients.')+'''<article class="example-sheet"><h2>Start here / a ten-minute first task</h2><ol><li>Pick one actual project. Copy the client-question fields into a document or use the worksheet below.</li><li>Write the reader and the one action the deliverable should support.</li><li>Fill confirmed facts; turn missing facts into questions for the client.</li><li>Use the filled copy project below as a reference for agreed work and delivery.</li><li>Agree the client instructions before making the work. Complete the final checks before requesting approval.</li></ol><p class="notice">Editable fields are temporary. Print or save a PDF before closing. For editable delivery, package an actual document/template file and test it with an unfamiliar reader.</p><h2>01 / Filled example</h2>'''+table(['Field','Fictional landing-page-copy project'],[
 ('Buyer & task','ClearFix Repairs wants people to understand its device-assessment process.'),('Reader & action','Device owner with an unclear issue; request an assessment.'),('Inputs','Approved service details, existing hero, opening hours, inquiry link, assessment terms.'),('Deliverables','One headline section, three benefit bullets, one contact button, three inquiry follow-up emails and a placement guide.'),('Exclusions','Site development, email sending, ad management and promised conversion lift.'),('Timing & revisions','Draft after complete client instructions; review date and one revision round agreed in writing.'),('Acceptance','Facts match the client facts; approved link works; reader understands the process; no unsupported claim.'),('Delivery','Numbered document sections, source notes, open questions and owner approval record.')])+ '<h2>02 / Your client instructions</h2>'+''.join(f'<div class="field"><label for="brief-{i}">{E(f)}</label><textarea id="brief-{i}"></textarea></div>' for i,f in enumerate(fields))+'<h2>03 / Plan the making steps</h2>'+table(['Stage','Your output','Pass check'],[(x,'[write your specific file or decision]','[what makes it ready]') for x in ['Collect facts','Agree the work','Make one section','Review claims and links','Package and request approval']])+'''<h2>04 / File checklist</h2><ul><li>Approved client facts and agreed work</li><li>Versioned draft and final deliverable</li><li>Source notes and unresolved questions</li><li>Client-owned or licensed asset record</li><li>Placement/use instructions and revision terms</li></ul><h2>05 / Approval message</h2><p>Hi [name], the agreed [deliverable] is ready at [link]. Please check the marked facts and final contact button. Your team will [implementation action]. Send the agreed revision round as one list by [date]. After approval I will deliver the final version and usage notes. If an input changed, flag it before publication.</p><h2>06 / Review log</h2>'''+table(['Question','Filled practice answer','Your answer'],[('What was delivered?','Headline, contact button and email drafts.',''),('Was it approved?','Pending client review.',''),('What took longer?','Waiting for assessment terms.',''),('Any measured business result?','None; no deployment data.',''),('Next process change?','Ask for fee/assessment terms in the first set of client instructions.','')])+'''<h2>07 / Seller packaging checklist</h2><p>This prototype includes instructions, a filled example, blank worksheets, an asset checklist, delivery messages and a review log. If selling your own version, provide a usable editable file plus PDF, show compatibility and exact contents, state your actual support/refund terms, and test delivery. Suggested practice $19 is an assumption to test, not proven willingness to pay.</p><p><a href="/playbooks/playbook-b-launch-product.html">Follow the product-validation playbook ↗</a></p></article><button class="no-print" data-print>Print workbook / save PDF</button>'''
 write('assets/samples/freelancer-project-starter.html','Freelancer Project Starter',product,'examples')
 (A/'carousel-storyboard.txt').write_text('''CAROUSEL / 7 SLIDES / 1080x1350
1. Would you pay for this AI draft? Show a short vague line.
2. The problem: unsupported claims and no clear next step. Mark the exact words.
3. Start with facts: reader, offer, approved details, Next action and rights. Show the filled brief.
4. Rewrite for one reader question. Show raw -> edited copy.
5. Same process, different buyers: fitness coach / repair service / online shop. Use three short excerpts.
6. A usable handoff: calendar, captions, layouts, QA and instructions. Show the real files.
7. Want the example? Ask for PREVIEW. Deliver the public preview manually when requested.
Keep one point per slide. Use title, checklist, screen crop and comparison layouts. Preview phone size, check numbered export order, and add image descriptions where supported. No reach or earnings promise.
''')
 (A/'lead-replies.txt').write_text('''MANUAL SAMPLE-TO-OFFER REPLIES
1. Deliver first: Here is the preview: https://app.zerotopaidwithai.com/preview. Compare the brief with the edited caption. Are you exploring client services or a reusable digital product?
2. Services: The route covers a scoped sample, researched prospects, permission-based outreach and delivery. Which step are you working on?
3. Products: The route covers buyer evidence, a complete usable download, delivery testing and demonstrations. What specific task would your buyer complete?
4. Relevant offer: The Blueprint is $97 one-time [confirm live checkout]. It includes ten playbooks, varied worked examples, free/paid tool routes, 50 action prompts, a 300-prompt reference vault and saved tasks/trackers. Here are the actual contents and terms: [verified offer link]. No income guarantee.
5. Price concern: Start with the free preview and tools you have. The paid product adds the sequence, prompts and full delivery references. Decide whether that helps your current task.
6. Guarantee question: I cannot promise a sale. The examples show work you can produce. Actual access/refund terms: [approved terms].
7. Agreed follow-up: You asked me to check back about [question]. Did you inspect the example? If your plans changed, no problem.
Log actual requests, deliveries, replies, permission to follow up, sales and available payouts separately. Stop after refusal.
''')
 scripts=[('The next step is clear','Open Start here. Click Get my track. Answer one question at a time. Show the saved route and its first task.'),('One process, different clients','Switch between a coach, repair business and shop. Show how the brief changes the caption, while the delivery process stays the same.'),('Fix the generic AI draft','Show the raw line, mark an unsupported claim, then reveal the edit supported by the brief.'),('The complete handoff','Open the calendar, seven captions, three layouts and handoff. Explain what the recipient can actually use.'),('A product someone can finish using','Open the Freelancer Project Starter. Fill one worksheet field and show the filled reference and approval message.'),('Free first, paid only for a bottleneck','Show the free and paid tool routes, then enter an actual credit cost in the calculator. Label practice numbers.'),('What the Blueprint includes','Show the sidebar, guided reader, examples and copyable prompts. State the actual $97 offer and no promised income.')]
 (A/'seven-video-scripts.txt').write_text('\n\n'.join(f'VIDEO {i}: {title}\n0-3s: show the final useful output.\n3-25s: {body}\n25-35s: Ask for PREVIEW if you want to inspect the example. Deliver manually.\nUse your own screen and voice. Label fictional inputs; show no invented revenue or client proof.' for i,(title,body) in enumerate(scripts,1)))
 # Preserve existing bookmarks while removing the previous niche from the visible curriculum.
 for old in ['salon-content-pack.html','salon-week-starter.html']:
  write('assets/samples/'+old,'Updated example',hero('Example updated','Choose the example that fits your work.','The worked examples now compare several business types and a reusable freelancer product.')+'<div class="actions"><a class="button" href="/assets/samples/content-delivery.html">Compare content deliveries ↗</a><a href="/assets/samples/freelancer-project-starter.html">Inspect the starter product ↗</a></div>','examples')
 for old in ['salon-calendar.csv','salon-layout-1.svg','salon-layout-2.svg','salon-layout-3.svg']:
  (A/old).unlink(missing_ok=True)
 return EXAMPLES

if __name__=='__main__':
 build_samples();print('Built three varied content deliveries and a complete reusable product.')
